version: "3.9"
services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "dnd_back"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - testdb-data:/var/lib/postgresql/data
  backend:
    build: .
    ports:
      - "1234:8080"


volumes:
  testdb-data:
