// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	JwtBearerScopes = "JwtBearer.Scopes"
)

// Defines values for CharacterObjectAlignment.
const (
	CE CharacterObjectAlignment = "CE"
	CG CharacterObjectAlignment = "CG"
	CN CharacterObjectAlignment = "CN"
	LE CharacterObjectAlignment = "LE"
	LG CharacterObjectAlignment = "LG"
	LN CharacterObjectAlignment = "LN"
	NE CharacterObjectAlignment = "NE"
	NG CharacterObjectAlignment = "NG"
	TN CharacterObjectAlignment = "TN"
)

// Valid indicates whether the value is a known member of the CharacterObjectAlignment enum.
func (e CharacterObjectAlignment) Valid() bool {
	switch e {
	case CE:
		return true
	case CG:
		return true
	case CN:
		return true
	case LE:
		return true
	case LG:
		return true
	case LN:
		return true
	case NE:
		return true
	case NG:
		return true
	case TN:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectAttacksDamageDiceValue.
const (
	CharacterObjectAttacksDamageDiceValueN10  CharacterObjectAttacksDamageDiceValue = 10
	CharacterObjectAttacksDamageDiceValueN100 CharacterObjectAttacksDamageDiceValue = 100
	CharacterObjectAttacksDamageDiceValueN12  CharacterObjectAttacksDamageDiceValue = 12
	CharacterObjectAttacksDamageDiceValueN20  CharacterObjectAttacksDamageDiceValue = 20
	CharacterObjectAttacksDamageDiceValueN4   CharacterObjectAttacksDamageDiceValue = 4
	CharacterObjectAttacksDamageDiceValueN8   CharacterObjectAttacksDamageDiceValue = 8
)

// Valid indicates whether the value is a known member of the CharacterObjectAttacksDamageDiceValue enum.
func (e CharacterObjectAttacksDamageDiceValue) Valid() bool {
	switch e {
	case CharacterObjectAttacksDamageDiceValueN10:
		return true
	case CharacterObjectAttacksDamageDiceValueN100:
		return true
	case CharacterObjectAttacksDamageDiceValueN12:
		return true
	case CharacterObjectAttacksDamageDiceValueN20:
		return true
	case CharacterObjectAttacksDamageDiceValueN4:
		return true
	case CharacterObjectAttacksDamageDiceValueN8:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectAttacksToHitAbility.
const (
	CharacterObjectAttacksToHitAbilityCHA CharacterObjectAttacksToHitAbility = "CHA"
	CharacterObjectAttacksToHitAbilityCON CharacterObjectAttacksToHitAbility = "CON"
	CharacterObjectAttacksToHitAbilityDEX CharacterObjectAttacksToHitAbility = "DEX"
	CharacterObjectAttacksToHitAbilityINT CharacterObjectAttacksToHitAbility = "INT"
	CharacterObjectAttacksToHitAbilitySTR CharacterObjectAttacksToHitAbility = "STR"
	CharacterObjectAttacksToHitAbilityWIS CharacterObjectAttacksToHitAbility = "WIS"
)

// Valid indicates whether the value is a known member of the CharacterObjectAttacksToHitAbility enum.
func (e CharacterObjectAttacksToHitAbility) Valid() bool {
	switch e {
	case CharacterObjectAttacksToHitAbilityCHA:
		return true
	case CharacterObjectAttacksToHitAbilityCON:
		return true
	case CharacterObjectAttacksToHitAbilityDEX:
		return true
	case CharacterObjectAttacksToHitAbilityINT:
		return true
	case CharacterObjectAttacksToHitAbilitySTR:
		return true
	case CharacterObjectAttacksToHitAbilityWIS:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectExpertises.
const (
	CharacterObjectExpertisesAcrobatics     CharacterObjectExpertises = "Acrobatics"
	CharacterObjectExpertisesAnimalHandling CharacterObjectExpertises = "Animal Handling"
	CharacterObjectExpertisesArcana         CharacterObjectExpertises = "Arcana"
	CharacterObjectExpertisesAthletics      CharacterObjectExpertises = "Athletics"
	CharacterObjectExpertisesDeception      CharacterObjectExpertises = "Deception"
	CharacterObjectExpertisesHistory        CharacterObjectExpertises = "History"
	CharacterObjectExpertisesInsight        CharacterObjectExpertises = "Insight"
	CharacterObjectExpertisesIntimidation   CharacterObjectExpertises = "Intimidation"
	CharacterObjectExpertisesInvestigation  CharacterObjectExpertises = "Investigation"
	CharacterObjectExpertisesMedicine       CharacterObjectExpertises = "Medicine"
	CharacterObjectExpertisesNature         CharacterObjectExpertises = "Nature"
	CharacterObjectExpertisesPerception     CharacterObjectExpertises = "Perception"
	CharacterObjectExpertisesPerformance    CharacterObjectExpertises = "Performance"
	CharacterObjectExpertisesPersuasion     CharacterObjectExpertises = "Persuasion"
	CharacterObjectExpertisesReligion       CharacterObjectExpertises = "Religion"
	CharacterObjectExpertisesSleightOfHand  CharacterObjectExpertises = "Sleight of hand"
	CharacterObjectExpertisesStealth        CharacterObjectExpertises = "Stealth"
	CharacterObjectExpertisesSurvival       CharacterObjectExpertises = "Survival"
)

// Valid indicates whether the value is a known member of the CharacterObjectExpertises enum.
func (e CharacterObjectExpertises) Valid() bool {
	switch e {
	case CharacterObjectExpertisesAcrobatics:
		return true
	case CharacterObjectExpertisesAnimalHandling:
		return true
	case CharacterObjectExpertisesArcana:
		return true
	case CharacterObjectExpertisesAthletics:
		return true
	case CharacterObjectExpertisesDeception:
		return true
	case CharacterObjectExpertisesHistory:
		return true
	case CharacterObjectExpertisesInsight:
		return true
	case CharacterObjectExpertisesIntimidation:
		return true
	case CharacterObjectExpertisesInvestigation:
		return true
	case CharacterObjectExpertisesMedicine:
		return true
	case CharacterObjectExpertisesNature:
		return true
	case CharacterObjectExpertisesPerception:
		return true
	case CharacterObjectExpertisesPerformance:
		return true
	case CharacterObjectExpertisesPersuasion:
		return true
	case CharacterObjectExpertisesReligion:
		return true
	case CharacterObjectExpertisesSleightOfHand:
		return true
	case CharacterObjectExpertisesStealth:
		return true
	case CharacterObjectExpertisesSurvival:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectHpHitDiceValue.
const (
	CharacterObjectHpHitDiceValueN10 CharacterObjectHpHitDiceValue = 10
	CharacterObjectHpHitDiceValueN12 CharacterObjectHpHitDiceValue = 12
	CharacterObjectHpHitDiceValueN20 CharacterObjectHpHitDiceValue = 20
	CharacterObjectHpHitDiceValueN4  CharacterObjectHpHitDiceValue = 4
	CharacterObjectHpHitDiceValueN8  CharacterObjectHpHitDiceValue = 8
)

// Valid indicates whether the value is a known member of the CharacterObjectHpHitDiceValue enum.
func (e CharacterObjectHpHitDiceValue) Valid() bool {
	switch e {
	case CharacterObjectHpHitDiceValueN10:
		return true
	case CharacterObjectHpHitDiceValueN12:
		return true
	case CharacterObjectHpHitDiceValueN20:
		return true
	case CharacterObjectHpHitDiceValueN4:
		return true
	case CharacterObjectHpHitDiceValueN8:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectProficiencies.
const (
	CharacterObjectProficienciesAcrobatics     CharacterObjectProficiencies = "Acrobatics"
	CharacterObjectProficienciesAnimalHandling CharacterObjectProficiencies = "Animal Handling"
	CharacterObjectProficienciesArcana         CharacterObjectProficiencies = "Arcana"
	CharacterObjectProficienciesAthletics      CharacterObjectProficiencies = "Athletics"
	CharacterObjectProficienciesDeception      CharacterObjectProficiencies = "Deception"
	CharacterObjectProficienciesHistory        CharacterObjectProficiencies = "History"
	CharacterObjectProficienciesInsight        CharacterObjectProficiencies = "Insight"
	CharacterObjectProficienciesIntimidation   CharacterObjectProficiencies = "Intimidation"
	CharacterObjectProficienciesInvestigation  CharacterObjectProficiencies = "Investigation"
	CharacterObjectProficienciesMedicine       CharacterObjectProficiencies = "Medicine"
	CharacterObjectProficienciesNature         CharacterObjectProficiencies = "Nature"
	CharacterObjectProficienciesPerception     CharacterObjectProficiencies = "Perception"
	CharacterObjectProficienciesPerformance    CharacterObjectProficiencies = "Performance"
	CharacterObjectProficienciesPersuasion     CharacterObjectProficiencies = "Persuasion"
	CharacterObjectProficienciesReligion       CharacterObjectProficiencies = "Religion"
	CharacterObjectProficienciesSleightOfHand  CharacterObjectProficiencies = "Sleight of hand"
	CharacterObjectProficienciesStealth        CharacterObjectProficiencies = "Stealth"
	CharacterObjectProficienciesSurvival       CharacterObjectProficiencies = "Survival"
)

// Valid indicates whether the value is a known member of the CharacterObjectProficiencies enum.
func (e CharacterObjectProficiencies) Valid() bool {
	switch e {
	case CharacterObjectProficienciesAcrobatics:
		return true
	case CharacterObjectProficienciesAnimalHandling:
		return true
	case CharacterObjectProficienciesArcana:
		return true
	case CharacterObjectProficienciesAthletics:
		return true
	case CharacterObjectProficienciesDeception:
		return true
	case CharacterObjectProficienciesHistory:
		return true
	case CharacterObjectProficienciesInsight:
		return true
	case CharacterObjectProficienciesIntimidation:
		return true
	case CharacterObjectProficienciesInvestigation:
		return true
	case CharacterObjectProficienciesMedicine:
		return true
	case CharacterObjectProficienciesNature:
		return true
	case CharacterObjectProficienciesPerception:
		return true
	case CharacterObjectProficienciesPerformance:
		return true
	case CharacterObjectProficienciesPersuasion:
		return true
	case CharacterObjectProficienciesReligion:
		return true
	case CharacterObjectProficienciesSleightOfHand:
		return true
	case CharacterObjectProficienciesStealth:
		return true
	case CharacterObjectProficienciesSurvival:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectSavingThrowProf.
const (
	CharacterObjectSavingThrowProfCHA CharacterObjectSavingThrowProf = "CHA"
	CharacterObjectSavingThrowProfCON CharacterObjectSavingThrowProf = "CON"
	CharacterObjectSavingThrowProfDEX CharacterObjectSavingThrowProf = "DEX"
	CharacterObjectSavingThrowProfINT CharacterObjectSavingThrowProf = "INT"
	CharacterObjectSavingThrowProfSTR CharacterObjectSavingThrowProf = "STR"
	CharacterObjectSavingThrowProfWIS CharacterObjectSavingThrowProf = "WIS"
)

// Valid indicates whether the value is a known member of the CharacterObjectSavingThrowProf enum.
func (e CharacterObjectSavingThrowProf) Valid() bool {
	switch e {
	case CharacterObjectSavingThrowProfCHA:
		return true
	case CharacterObjectSavingThrowProfCON:
		return true
	case CharacterObjectSavingThrowProfDEX:
		return true
	case CharacterObjectSavingThrowProfINT:
		return true
	case CharacterObjectSavingThrowProfSTR:
		return true
	case CharacterObjectSavingThrowProfWIS:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectSize.
const (
	Colossal   CharacterObjectSize = "Colossal"
	Diminutive CharacterObjectSize = "Diminutive"
	Fine       CharacterObjectSize = "Fine"
	Gargantuan CharacterObjectSize = "Gargantuan"
	Huge       CharacterObjectSize = "Huge"
	Large      CharacterObjectSize = "Large"
	Medium     CharacterObjectSize = "Medium"
	Small      CharacterObjectSize = "Small"
	Tiny       CharacterObjectSize = "Tiny"
)

// Valid indicates whether the value is a known member of the CharacterObjectSize enum.
func (e CharacterObjectSize) Valid() bool {
	switch e {
	case Colossal:
		return true
	case Diminutive:
		return true
	case Fine:
		return true
	case Gargantuan:
		return true
	case Huge:
		return true
	case Large:
		return true
	case Medium:
		return true
	case Small:
		return true
	case Tiny:
		return true
	default:
		return false
	}
}

// Defines values for ItemObjectItemType.
const (
	ItemObjectItemTypeArmour    ItemObjectItemType = "Armour"
	ItemObjectItemTypeArtefact  ItemObjectItemType = "Artefact"
	ItemObjectItemTypeContainer ItemObjectItemType = "Container"
	ItemObjectItemTypeOther     ItemObjectItemType = "Other"
	ItemObjectItemTypeWeapon    ItemObjectItemType = "Weapon"
)

// Valid indicates whether the value is a known member of the ItemObjectItemType enum.
func (e ItemObjectItemType) Valid() bool {
	switch e {
	case ItemObjectItemTypeArmour:
		return true
	case ItemObjectItemTypeArtefact:
		return true
	case ItemObjectItemTypeContainer:
		return true
	case ItemObjectItemTypeOther:
		return true
	case ItemObjectItemTypeWeapon:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectDurationDurationType.
const (
	Days           SpellObjectDurationDurationType = "Days"
	Hours          SpellObjectDurationDurationType = "Hours"
	Instant        SpellObjectDurationDurationType = "Instant"
	Minutes        SpellObjectDurationDurationType = "Minutes"
	UntilDispelled SpellObjectDurationDurationType = "Until dispelled"
)

// Valid indicates whether the value is a known member of the SpellObjectDurationDurationType enum.
func (e SpellObjectDurationDurationType) Valid() bool {
	switch e {
	case Days:
		return true
	case Hours:
		return true
	case Instant:
		return true
	case Minutes:
		return true
	case UntilDispelled:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectEffectAbility.
const (
	CHA SpellObjectEffectAbility = "CHA"
	CON SpellObjectEffectAbility = "CON"
	DEX SpellObjectEffectAbility = "DEX"
	INT SpellObjectEffectAbility = "INT"
	STR SpellObjectEffectAbility = "STR"
	WIS SpellObjectEffectAbility = "WIS"
)

// Valid indicates whether the value is a known member of the SpellObjectEffectAbility enum.
func (e SpellObjectEffectAbility) Valid() bool {
	switch e {
	case CHA:
		return true
	case CON:
		return true
	case DEX:
		return true
	case INT:
		return true
	case STR:
		return true
	case WIS:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectEffectDiceValue.
const (
	SpellObjectEffectDiceValueN10  SpellObjectEffectDiceValue = 10
	SpellObjectEffectDiceValueN100 SpellObjectEffectDiceValue = 100
	SpellObjectEffectDiceValueN12  SpellObjectEffectDiceValue = 12
	SpellObjectEffectDiceValueN20  SpellObjectEffectDiceValue = 20
	SpellObjectEffectDiceValueN4   SpellObjectEffectDiceValue = 4
	SpellObjectEffectDiceValueN8   SpellObjectEffectDiceValue = 8
)

// Valid indicates whether the value is a known member of the SpellObjectEffectDiceValue enum.
func (e SpellObjectEffectDiceValue) Valid() bool {
	switch e {
	case SpellObjectEffectDiceValueN10:
		return true
	case SpellObjectEffectDiceValueN100:
		return true
	case SpellObjectEffectDiceValueN12:
		return true
	case SpellObjectEffectDiceValueN20:
		return true
	case SpellObjectEffectDiceValueN4:
		return true
	case SpellObjectEffectDiceValueN8:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectEffectEffect.
const (
	SpellObjectEffectEffectHeal   SpellObjectEffectEffect = "Heal"
	SpellObjectEffectEffectMelee  SpellObjectEffectEffect = "Melee"
	SpellObjectEffectEffectOther  SpellObjectEffectEffect = "Other"
	SpellObjectEffectEffectRanged SpellObjectEffectEffect = "Ranged"
	SpellObjectEffectEffectSave   SpellObjectEffectEffect = "Save"
)

// Valid indicates whether the value is a known member of the SpellObjectEffectEffect enum.
func (e SpellObjectEffectEffect) Valid() bool {
	switch e {
	case SpellObjectEffectEffectHeal:
		return true
	case SpellObjectEffectEffectMelee:
		return true
	case SpellObjectEffectEffectOther:
		return true
	case SpellObjectEffectEffectRanged:
		return true
	case SpellObjectEffectEffectSave:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectRangeRangeType.
const (
	Any   SpellObjectRangeRangeType = "Any"
	Feet  SpellObjectRangeRangeType = "Feet"
	Miles SpellObjectRangeRangeType = "Miles"
	Self  SpellObjectRangeRangeType = "Self"
	Touch SpellObjectRangeRangeType = "Touch"
)

// Valid indicates whether the value is a known member of the SpellObjectRangeRangeType enum.
func (e SpellObjectRangeRangeType) Valid() bool {
	switch e {
	case Any:
		return true
	case Feet:
		return true
	case Miles:
		return true
	case Self:
		return true
	case Touch:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectTimeToCastTime.
const (
	Action      SpellObjectTimeToCastTime = "Action"
	BonusAction SpellObjectTimeToCastTime = "Bonus Action"
	Reaction    SpellObjectTimeToCastTime = "Reaction"
	Rounds      SpellObjectTimeToCastTime = "Rounds"
)

// Valid indicates whether the value is a known member of the SpellObjectTimeToCastTime enum.
func (e SpellObjectTimeToCastTime) Valid() bool {
	switch e {
	case Action:
		return true
	case BonusAction:
		return true
	case Reaction:
		return true
	case Rounds:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectUpcastDiceValue.
const (
	SpellObjectUpcastDiceValueN10  SpellObjectUpcastDiceValue = 10
	SpellObjectUpcastDiceValueN100 SpellObjectUpcastDiceValue = 100
	SpellObjectUpcastDiceValueN12  SpellObjectUpcastDiceValue = 12
	SpellObjectUpcastDiceValueN20  SpellObjectUpcastDiceValue = 20
	SpellObjectUpcastDiceValueN4   SpellObjectUpcastDiceValue = 4
	SpellObjectUpcastDiceValueN8   SpellObjectUpcastDiceValue = 8
)

// Valid indicates whether the value is a known member of the SpellObjectUpcastDiceValue enum.
func (e SpellObjectUpcastDiceValue) Valid() bool {
	switch e {
	case SpellObjectUpcastDiceValueN10:
		return true
	case SpellObjectUpcastDiceValueN100:
		return true
	case SpellObjectUpcastDiceValueN12:
		return true
	case SpellObjectUpcastDiceValueN20:
		return true
	case SpellObjectUpcastDiceValueN4:
		return true
	case SpellObjectUpcastDiceValueN8:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectUpcastUpcastType.
const (
	Cantrip SpellObjectUpcastUpcastType = "Cantrip"
	Level   SpellObjectUpcastUpcastType = "Level"
)

// Valid indicates whether the value is a known member of the SpellObjectUpcastUpcastType enum.
func (e SpellObjectUpcastUpcastType) Valid() bool {
	switch e {
	case Cantrip:
		return true
	case Level:
		return true
	default:
		return false
	}
}

// CharacterObject defines model for CharacterObject.
type CharacterObject struct {
	Abilities struct {
		Cha uint `json:"cha"`
		Con uint `json:"con"`
		Dex uint `json:"dex"`
		Int uint `json:"int"`
		Str uint `json:"str"`
		Wis uint `json:"wis"`
	} `json:"abilities"`
	Ac                uint                     `json:"ac"`
	Age               string                   `json:"age"`
	Alignment         CharacterObjectAlignment `json:"alignment"`
	Allies            string                   `json:"allies"`
	Appearance        string                   `json:"appearance"`
	ArmourProficiency []string                 `json:"armour_proficiency"`
	Attacks           []struct {
		Damage struct {
			Bonus uint `json:"bonus"`
			Dice  struct {
				Amount uint                                  `json:"amount"`
				Value  CharacterObjectAttacksDamageDiceValue `json:"value"`
			} `json:"dice"`
		} `json:"damage"`
		Name  string   `json:"name"`
		Notes []string `json:"notes"`
		ToHit struct {
			Ability CharacterObjectAttacksToHitAbility `json:"ability"`
			Bonus   uint                               `json:"bonus"`
		} `json:"to_hit"`
	} `json:"attacks"`
	Background struct {
		Description string `json:"description"`
		Name        string `json:"name"`
	} `json:"background"`
	Backstory    string `json:"backstory"`
	Bonds        string `json:"bonds"`
	BonusActions []struct {
		FlavourText string                 `json:"flavour_text"`
		Name        string                 `json:"name"`
		OtherData   map[string]interface{} `json:"other_data"`
	} `json:"bonus_actions"`
	Capacity uint `json:"capacity"`
	Class    []struct {
		Level    *uint   `json:"level,omitempty"`
		Name     *string `json:"name,omitempty"`
		Subclass *string `json:"subclass,omitempty"`
	} `json:"class"`
	ClassFeatures []struct {
		Features []struct {
			Description string `json:"description"`
			Name        string `json:"name"`
		} `json:"features"`
		Name string `json:"name"`
	} `json:"class_features"`
	Conditions []string `json:"conditions"`
	DeathSaves struct {
		Failure uint `json:"failure"`
		Success uint `json:"success"`
	} `json:"death_saves"`
	Defences struct {
		Custom     []string `json:"custom"`
		Immune     []string `json:"immune"`
		Resistance []string `json:"resistance"`
		Vulnerable []string `json:"vulnerable"`
	} `json:"defences"`
	Enemies    string                      `json:"enemies"`
	Expertises []CharacterObjectExpertises `json:"expertises"`
	Eyes       string                      `json:"eyes"`
	Faith      string                      `json:"faith"`
	Feats      []FeatObject                `json:"feats"`
	Flaws      string                      `json:"flaws"`
	Gender     string                      `json:"gender"`
	Hair       string                      `json:"hair"`
	Height     string                      `json:"height"`
	Hp         struct {
		Current uint `json:"current"`
		HitDice struct {
			Left  uint                          `json:"left"`
			Max   uint                          `json:"max"`
			Value CharacterObjectHpHitDiceValue `json:"value"`
		} `json:"hit_dice"`
		Max  uint `json:"max"`
		Temp uint `json:"temp"`
	} `json:"hp"`
	Ideals        string       `json:"ideals"`
	InitiativeMod int          `json:"initiative_mod"`
	Inventory     []ItemObject `json:"inventory"`
	Languages     []string     `json:"languages"`
	Level         uint         `json:"level"`
	Money         struct {
		Cp uint `json:"cp"`
		Ep uint `json:"ep"`
		Gp uint `json:"gp"`
		Pp uint `json:"pp"`
		Sp uint `json:"sp"`
	} `json:"money"`
	Name           string                         `json:"name"`
	Notes          string                         `json:"notes"`
	Organizations  string                         `json:"organizations"`
	Personality    string                         `json:"personality"`
	Picture        string                         `json:"picture"`
	Proficiencies  []CharacterObjectProficiencies `json:"proficiencies"`
	ProficiencyMod uint                           `json:"proficiency_mod"`
	Race           string                         `json:"race"`
	RaceTraits     []struct {
		Description string `json:"description"`
		Name        string `json:"name"`
	} `json:"race_traits"`
	SavingThrowProf []CharacterObjectSavingThrowProf `json:"saving_throw_prof"`
	Senses          struct {
		Other                []string `json:"other"`
		PassiveInsight       uint     `json:"passive_insight"`
		PassiveInvestigation uint     `json:"passive_investigation"`
		PassivePerception    uint     `json:"passive_perception"`
	} `json:"senses"`
	Shielded bool                `json:"shielded"`
	Size     CharacterObjectSize `json:"size"`
	Skin     string              `json:"skin"`
	Speed    uint                `json:"speed"`
	Spells   struct {
		CurrentConcentration SpellObject   `json:"current_concentration"`
		KnownSpells          []SpellObject `json:"known_spells"`
		ReadySpells          []SpellObject `json:"ready_spells"`
	} `json:"spells"`
	ToolsProficiency  []string `json:"tools_proficiency"`
	WeaponProficiency []string `json:"weapon_proficiency"`
	Weight            uint     `json:"weight"`
	Xp                uint     `json:"xp"`
}

// CharacterObjectAlignment defines model for CharacterObject.Alignment.
type CharacterObjectAlignment string

// CharacterObjectAttacksDamageDiceValue defines model for CharacterObject.Attacks.Damage.Dice.Value.
type CharacterObjectAttacksDamageDiceValue int

// CharacterObjectAttacksToHitAbility defines model for CharacterObject.Attacks.ToHit.Ability.
type CharacterObjectAttacksToHitAbility string

// CharacterObjectExpertises defines model for CharacterObject.Expertises.
type CharacterObjectExpertises string

// CharacterObjectHpHitDiceValue defines model for CharacterObject.Hp.HitDice.Value.
type CharacterObjectHpHitDiceValue int

// CharacterObjectProficiencies defines model for CharacterObject.Proficiencies.
type CharacterObjectProficiencies string

// CharacterObjectSavingThrowProf defines model for CharacterObject.SavingThrowProf.
type CharacterObjectSavingThrowProf string

// CharacterObjectSize defines model for CharacterObject.Size.
type CharacterObjectSize string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message"`
}

// FeatObject defines model for FeatObject.
type FeatObject struct {
	Benefits      string `json:"benefits"`
	Name          string `json:"name"`
	Prerequisites string `json:"prerequisites"`
}

// ItemObject defines model for ItemObject.
type ItemObject struct {
	Cost     uint                   `json:"cost"`
	Data     map[string]interface{} `json:"data"`
	ItemType ItemObjectItemType     `json:"item_type"`
	Name     string                 `json:"name"`
	Weight   float32                `json:"weight"`
}

// ItemObjectItemType defines model for ItemObject.ItemType.
type ItemObjectItemType string

// RegisteredUserStructure defines model for RegisteredUserStructure.
type RegisteredUserStructure struct {
	Token    string `json:"token"`
	Username string `json:"username"`
}

// SpellObject defines model for SpellObject.
type SpellObject struct {
	Components struct {
		Material struct {
			Components string `json:"components"`
			Status     bool   `json:"status"`
		} `json:"material"`
		Somatic bool `json:"somatic"`
		Verbal  bool `json:"verbal"`
	} `json:"components"`
	Concentration bool   `json:"concentration"`
	Description   string `json:"description"`
	Duration      struct {
		Duration     int                             `json:"duration"`
		DurationType SpellObjectDurationDurationType `json:"duration_type"`
	} `json:"duration"`
	Effect struct {
		Ability SpellObjectEffectAbility `json:"ability"`
		Dice    struct {
			Amount uint                       `json:"amount"`
			Bonus  uint                       `json:"bonus"`
			Value  SpellObjectEffectDiceValue `json:"value"`
		} `json:"dice"`
		DmgType string                  `json:"dmg_type"`
		Effect  SpellObjectEffectEffect `json:"effect"`
	} `json:"effect"`
	Level uint   `json:"level"`
	Name  string `json:"name"`
	Range struct {
		Amount    int                       `json:"amount"`
		Notes     string                    `json:"notes"`
		RangeType SpellObjectRangeRangeType `json:"range_type"`
	} `json:"range"`
	Ritual bool   `json:"ritual"`
	School string `json:"school"`
	Target struct {
		Size       uint   `json:"size"`
		TargetType string `json:"target_type"`
	} `json:"target"`
	TimeToCast struct {
		Amount uint                      `json:"amount"`
		Notes  string                    `json:"notes"`
		Time   SpellObjectTimeToCastTime `json:"time"`
	} `json:"time_to_cast"`
	Upcast struct {
		Dice struct {
			Amount uint                       `json:"amount"`
			Value  SpellObjectUpcastDiceValue `json:"value"`
		} `json:"dice"`
		UpcastType SpellObjectUpcastUpcastType `json:"upcast_type"`
	} `json:"upcast"`
}

// SpellObjectDurationDurationType defines model for SpellObject.Duration.DurationType.
type SpellObjectDurationDurationType string

// SpellObjectEffectAbility defines model for SpellObject.Effect.Ability.
type SpellObjectEffectAbility string

// SpellObjectEffectDiceValue defines model for SpellObject.Effect.Dice.Value.
type SpellObjectEffectDiceValue int

// SpellObjectEffectEffect defines model for SpellObject.Effect.Effect.
type SpellObjectEffectEffect string

// SpellObjectRangeRangeType defines model for SpellObject.Range.RangeType.
type SpellObjectRangeRangeType string

// SpellObjectTimeToCastTime defines model for SpellObject.TimeToCast.Time.
type SpellObjectTimeToCastTime string

// SpellObjectUpcastDiceValue defines model for SpellObject.Upcast.Dice.Value.
type SpellObjectUpcastDiceValue int

// SpellObjectUpcastUpcastType defines model for SpellObject.Upcast.UpcastType.
type SpellObjectUpcastUpcastType string

// UserStructure defines model for UserStructure.
type UserStructure struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// PostApiDeleteCharacterJSONBody defines parameters for PostApiDeleteCharacter.
type PostApiDeleteCharacterJSONBody struct {
	Id int `json:"id"`
}

// PostApiDeleteItemJSONBody defines parameters for PostApiDeleteItem.
type PostApiDeleteItemJSONBody struct {
	Id int `json:"id"`
}

// PostApiDeleteSpellJSONBody defines parameters for PostApiDeleteSpell.
type PostApiDeleteSpellJSONBody struct {
	Id int `json:"id"`
}

// GetApiGetCharacterParams defines parameters for GetApiGetCharacter.
type GetApiGetCharacterParams struct {
	Id int `form:"id" json:"id"`
}

// PostApiUpdateCharacterJSONBody defines parameters for PostApiUpdateCharacter.
type PostApiUpdateCharacterJSONBody struct {
	Character CharacterObject `json:"character"`
	Id        int             `json:"id"`
}

// PostApiDeleteCharacterJSONRequestBody defines body for PostApiDeleteCharacter for application/json ContentType.
type PostApiDeleteCharacterJSONRequestBody PostApiDeleteCharacterJSONBody

// PostApiDeleteItemJSONRequestBody defines body for PostApiDeleteItem for application/json ContentType.
type PostApiDeleteItemJSONRequestBody PostApiDeleteItemJSONBody

// PostApiDeleteSpellJSONRequestBody defines body for PostApiDeleteSpell for application/json ContentType.
type PostApiDeleteSpellJSONRequestBody PostApiDeleteSpellJSONBody

// PostApiLoginJSONRequestBody defines body for PostApiLogin for application/json ContentType.
type PostApiLoginJSONRequestBody = UserStructure

// PostApiNewCharacterJSONRequestBody defines body for PostApiNewCharacter for application/json ContentType.
type PostApiNewCharacterJSONRequestBody = CharacterObject

// PostApiNewItemJSONRequestBody defines body for PostApiNewItem for application/json ContentType.
type PostApiNewItemJSONRequestBody = ItemObject

// PostApiNewSpellJSONRequestBody defines body for PostApiNewSpell for application/json ContentType.
type PostApiNewSpellJSONRequestBody = SpellObject

// PostApiRegisterJSONRequestBody defines body for PostApiRegister for application/json ContentType.
type PostApiRegisterJSONRequestBody = UserStructure

// PostApiUpdateCharacterJSONRequestBody defines body for PostApiUpdateCharacter for application/json ContentType.
type PostApiUpdateCharacterJSONRequestBody PostApiUpdateCharacterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/delete_character)
	PostApiDeleteCharacter(w http.ResponseWriter, r *http.Request)

	// (POST /api/delete_item)
	PostApiDeleteItem(w http.ResponseWriter, r *http.Request)

	// (POST /api/delete_spell)
	PostApiDeleteSpell(w http.ResponseWriter, r *http.Request)

	// (GET /api/get_all_items)
	GetApiGetAllItems(w http.ResponseWriter, r *http.Request)

	// (GET /api/get_all_spells)
	GetApiGetAllSpells(w http.ResponseWriter, r *http.Request)

	// (GET /api/get_character)
	GetApiGetCharacter(w http.ResponseWriter, r *http.Request, params GetApiGetCharacterParams)

	// (GET /api/list_characters)
	GetApiListCharacters(w http.ResponseWriter, r *http.Request)

	// (POST /api/login)
	PostApiLogin(w http.ResponseWriter, r *http.Request)

	// (POST /api/new_character)
	PostApiNewCharacter(w http.ResponseWriter, r *http.Request)

	// (POST /api/new_item)
	PostApiNewItem(w http.ResponseWriter, r *http.Request)

	// (POST /api/new_spell)
	PostApiNewSpell(w http.ResponseWriter, r *http.Request)

	// (POST /api/register)
	PostApiRegister(w http.ResponseWriter, r *http.Request)

	// (POST /api/update_character)
	PostApiUpdateCharacter(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /api/delete_character)
func (_ Unimplemented) PostApiDeleteCharacter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/delete_item)
func (_ Unimplemented) PostApiDeleteItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/delete_spell)
func (_ Unimplemented) PostApiDeleteSpell(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/get_all_items)
func (_ Unimplemented) GetApiGetAllItems(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/get_all_spells)
func (_ Unimplemented) GetApiGetAllSpells(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/get_character)
func (_ Unimplemented) GetApiGetCharacter(w http.ResponseWriter, r *http.Request, params GetApiGetCharacterParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/list_characters)
func (_ Unimplemented) GetApiListCharacters(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/login)
func (_ Unimplemented) PostApiLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/new_character)
func (_ Unimplemented) PostApiNewCharacter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/new_item)
func (_ Unimplemented) PostApiNewItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/new_spell)
func (_ Unimplemented) PostApiNewSpell(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/register)
func (_ Unimplemented) PostApiRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/update_character)
func (_ Unimplemented) PostApiUpdateCharacter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiDeleteCharacter operation middleware
func (siw *ServerInterfaceWrapper) PostApiDeleteCharacter(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDeleteCharacter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiDeleteItem operation middleware
func (siw *ServerInterfaceWrapper) PostApiDeleteItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDeleteItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiDeleteSpell operation middleware
func (siw *ServerInterfaceWrapper) PostApiDeleteSpell(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDeleteSpell(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGetAllItems operation middleware
func (siw *ServerInterfaceWrapper) GetApiGetAllItems(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGetAllItems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGetAllSpells operation middleware
func (siw *ServerInterfaceWrapper) GetApiGetAllSpells(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGetAllSpells(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGetCharacter operation middleware
func (siw *ServerInterfaceWrapper) GetApiGetCharacter(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiGetCharacterParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGetCharacter(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiListCharacters operation middleware
func (siw *ServerInterfaceWrapper) GetApiListCharacters(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiListCharacters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiLogin operation middleware
func (siw *ServerInterfaceWrapper) PostApiLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiNewCharacter operation middleware
func (siw *ServerInterfaceWrapper) PostApiNewCharacter(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiNewCharacter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiNewItem operation middleware
func (siw *ServerInterfaceWrapper) PostApiNewItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiNewItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiNewSpell operation middleware
func (siw *ServerInterfaceWrapper) PostApiNewSpell(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiNewSpell(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiRegister operation middleware
func (siw *ServerInterfaceWrapper) PostApiRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiUpdateCharacter operation middleware
func (siw *ServerInterfaceWrapper) PostApiUpdateCharacter(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiUpdateCharacter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/delete_character", wrapper.PostApiDeleteCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/delete_item", wrapper.PostApiDeleteItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/delete_spell", wrapper.PostApiDeleteSpell)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/get_all_items", wrapper.GetApiGetAllItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/get_all_spells", wrapper.GetApiGetAllSpells)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/get_character", wrapper.GetApiGetCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/list_characters", wrapper.GetApiListCharacters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/login", wrapper.PostApiLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/new_character", wrapper.PostApiNewCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/new_item", wrapper.PostApiNewItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/new_spell", wrapper.PostApiNewSpell)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/register", wrapper.PostApiRegister)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/update_character", wrapper.PostApiUpdateCharacter)
	})

	return r
}

type PostApiDeleteCharacterRequestObject struct {
	Body *PostApiDeleteCharacterJSONRequestBody
}

type PostApiDeleteCharacterResponseObject interface {
	VisitPostApiDeleteCharacterResponse(w http.ResponseWriter) error
}

type PostApiDeleteCharacter200JSONResponse struct {
	Character CharacterObject `json:"character"`
	Id        int             `json:"id"`
}

func (response PostApiDeleteCharacter200JSONResponse) VisitPostApiDeleteCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteCharacter400JSONResponse struct {
	Id      int    `json:"id"`
	Message string `json:"message"`
}

func (response PostApiDeleteCharacter400JSONResponse) VisitPostApiDeleteCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteCharacter401JSONResponse ErrorResponse

func (response PostApiDeleteCharacter401JSONResponse) VisitPostApiDeleteCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteCharacter500JSONResponse ErrorResponse

func (response PostApiDeleteCharacter500JSONResponse) VisitPostApiDeleteCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteItemRequestObject struct {
	Body *PostApiDeleteItemJSONRequestBody
}

type PostApiDeleteItemResponseObject interface {
	VisitPostApiDeleteItemResponse(w http.ResponseWriter) error
}

type PostApiDeleteItem200JSONResponse struct {
	Id   int        `json:"id"`
	Item ItemObject `json:"item"`
}

func (response PostApiDeleteItem200JSONResponse) VisitPostApiDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteItem401JSONResponse ErrorResponse

func (response PostApiDeleteItem401JSONResponse) VisitPostApiDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteItem500JSONResponse ErrorResponse

func (response PostApiDeleteItem500JSONResponse) VisitPostApiDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteSpellRequestObject struct {
	Body *PostApiDeleteSpellJSONRequestBody
}

type PostApiDeleteSpellResponseObject interface {
	VisitPostApiDeleteSpellResponse(w http.ResponseWriter) error
}

type PostApiDeleteSpell200JSONResponse struct {
	Id    int         `json:"id"`
	Spell SpellObject `json:"spell"`
}

func (response PostApiDeleteSpell200JSONResponse) VisitPostApiDeleteSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteSpell401JSONResponse ErrorResponse

func (response PostApiDeleteSpell401JSONResponse) VisitPostApiDeleteSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteSpell500JSONResponse ErrorResponse

func (response PostApiDeleteSpell500JSONResponse) VisitPostApiDeleteSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllItemsRequestObject struct {
}

type GetApiGetAllItemsResponseObject interface {
	VisitGetApiGetAllItemsResponse(w http.ResponseWriter) error
}

type GetApiGetAllItems200JSONResponse []ItemObject

func (response GetApiGetAllItems200JSONResponse) VisitGetApiGetAllItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllItems401JSONResponse ErrorResponse

func (response GetApiGetAllItems401JSONResponse) VisitGetApiGetAllItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllItems500JSONResponse ErrorResponse

func (response GetApiGetAllItems500JSONResponse) VisitGetApiGetAllItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllSpellsRequestObject struct {
}

type GetApiGetAllSpellsResponseObject interface {
	VisitGetApiGetAllSpellsResponse(w http.ResponseWriter) error
}

type GetApiGetAllSpells200JSONResponse []SpellObject

func (response GetApiGetAllSpells200JSONResponse) VisitGetApiGetAllSpellsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllSpells401JSONResponse ErrorResponse

func (response GetApiGetAllSpells401JSONResponse) VisitGetApiGetAllSpellsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllSpells500JSONResponse ErrorResponse

func (response GetApiGetAllSpells500JSONResponse) VisitGetApiGetAllSpellsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetCharacterRequestObject struct {
	Params GetApiGetCharacterParams
}

type GetApiGetCharacterResponseObject interface {
	VisitGetApiGetCharacterResponse(w http.ResponseWriter) error
}

type GetApiGetCharacter200JSONResponse CharacterObject

func (response GetApiGetCharacter200JSONResponse) VisitGetApiGetCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetCharacter400JSONResponse struct {
	Id      int    `json:"id"`
	Message string `json:"message"`
}

func (response GetApiGetCharacter400JSONResponse) VisitGetApiGetCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetCharacter401JSONResponse ErrorResponse

func (response GetApiGetCharacter401JSONResponse) VisitGetApiGetCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetCharacter500JSONResponse ErrorResponse

func (response GetApiGetCharacter500JSONResponse) VisitGetApiGetCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiListCharactersRequestObject struct {
}

type GetApiListCharactersResponseObject interface {
	VisitGetApiListCharactersResponse(w http.ResponseWriter) error
}

type GetApiListCharacters200JSONResponse []struct {
	Class   string `json:"class"`
	Id      int    `json:"id"`
	Level   uint   `json:"level"`
	Name    string `json:"name"`
	Picture string `json:"picture"`
	Race    string `json:"race"`
}

func (response GetApiListCharacters200JSONResponse) VisitGetApiListCharactersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiListCharacters401JSONResponse ErrorResponse

func (response GetApiListCharacters401JSONResponse) VisitGetApiListCharactersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetApiListCharacters500JSONResponse ErrorResponse

func (response GetApiListCharacters500JSONResponse) VisitGetApiListCharactersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiLoginRequestObject struct {
	Body *PostApiLoginJSONRequestBody
}

type PostApiLoginResponseObject interface {
	VisitPostApiLoginResponse(w http.ResponseWriter) error
}

type PostApiLogin200JSONResponse RegisteredUserStructure

func (response PostApiLogin200JSONResponse) VisitPostApiLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiLogin401JSONResponse UserStructure

func (response PostApiLogin401JSONResponse) VisitPostApiLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiLogin500JSONResponse ErrorResponse

func (response PostApiLogin500JSONResponse) VisitPostApiLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewCharacterRequestObject struct {
	Body *PostApiNewCharacterJSONRequestBody
}

type PostApiNewCharacterResponseObject interface {
	VisitPostApiNewCharacterResponse(w http.ResponseWriter) error
}

type PostApiNewCharacter200JSONResponse struct {
	Character CharacterObject `json:"character"`
	Id        int             `json:"id"`
}

func (response PostApiNewCharacter200JSONResponse) VisitPostApiNewCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewCharacter401JSONResponse ErrorResponse

func (response PostApiNewCharacter401JSONResponse) VisitPostApiNewCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewCharacter500JSONResponse ErrorResponse

func (response PostApiNewCharacter500JSONResponse) VisitPostApiNewCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewItemRequestObject struct {
	Body *PostApiNewItemJSONRequestBody
}

type PostApiNewItemResponseObject interface {
	VisitPostApiNewItemResponse(w http.ResponseWriter) error
}

type PostApiNewItem200JSONResponse struct {
	Id   int        `json:"id"`
	Item ItemObject `json:"item"`
}

func (response PostApiNewItem200JSONResponse) VisitPostApiNewItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewItem401JSONResponse ErrorResponse

func (response PostApiNewItem401JSONResponse) VisitPostApiNewItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewItem500JSONResponse ErrorResponse

func (response PostApiNewItem500JSONResponse) VisitPostApiNewItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewSpellRequestObject struct {
	Body *PostApiNewSpellJSONRequestBody
}

type PostApiNewSpellResponseObject interface {
	VisitPostApiNewSpellResponse(w http.ResponseWriter) error
}

type PostApiNewSpell200JSONResponse struct {
	Id    int         `json:"id"`
	Spell SpellObject `json:"spell"`
}

func (response PostApiNewSpell200JSONResponse) VisitPostApiNewSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewSpell401JSONResponse ErrorResponse

func (response PostApiNewSpell401JSONResponse) VisitPostApiNewSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewSpell500JSONResponse ErrorResponse

func (response PostApiNewSpell500JSONResponse) VisitPostApiNewSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiRegisterRequestObject struct {
	Body *PostApiRegisterJSONRequestBody
}

type PostApiRegisterResponseObject interface {
	VisitPostApiRegisterResponse(w http.ResponseWriter) error
}

type PostApiRegister200JSONResponse RegisteredUserStructure

func (response PostApiRegister200JSONResponse) VisitPostApiRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiRegister400JSONResponse UserStructure

func (response PostApiRegister400JSONResponse) VisitPostApiRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiRegister500JSONResponse ErrorResponse

func (response PostApiRegister500JSONResponse) VisitPostApiRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiUpdateCharacterRequestObject struct {
	Body *PostApiUpdateCharacterJSONRequestBody
}

type PostApiUpdateCharacterResponseObject interface {
	VisitPostApiUpdateCharacterResponse(w http.ResponseWriter) error
}

type PostApiUpdateCharacter200JSONResponse CharacterObject

func (response PostApiUpdateCharacter200JSONResponse) VisitPostApiUpdateCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiUpdateCharacter400JSONResponse struct {
	Id      int    `json:"id"`
	Message string `json:"message"`
}

func (response PostApiUpdateCharacter400JSONResponse) VisitPostApiUpdateCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiUpdateCharacter401JSONResponse ErrorResponse

func (response PostApiUpdateCharacter401JSONResponse) VisitPostApiUpdateCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiUpdateCharacter500JSONResponse ErrorResponse

func (response PostApiUpdateCharacter500JSONResponse) VisitPostApiUpdateCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/delete_character)
	PostApiDeleteCharacter(ctx context.Context, request PostApiDeleteCharacterRequestObject) (PostApiDeleteCharacterResponseObject, error)

	// (POST /api/delete_item)
	PostApiDeleteItem(ctx context.Context, request PostApiDeleteItemRequestObject) (PostApiDeleteItemResponseObject, error)

	// (POST /api/delete_spell)
	PostApiDeleteSpell(ctx context.Context, request PostApiDeleteSpellRequestObject) (PostApiDeleteSpellResponseObject, error)

	// (GET /api/get_all_items)
	GetApiGetAllItems(ctx context.Context, request GetApiGetAllItemsRequestObject) (GetApiGetAllItemsResponseObject, error)

	// (GET /api/get_all_spells)
	GetApiGetAllSpells(ctx context.Context, request GetApiGetAllSpellsRequestObject) (GetApiGetAllSpellsResponseObject, error)

	// (GET /api/get_character)
	GetApiGetCharacter(ctx context.Context, request GetApiGetCharacterRequestObject) (GetApiGetCharacterResponseObject, error)

	// (GET /api/list_characters)
	GetApiListCharacters(ctx context.Context, request GetApiListCharactersRequestObject) (GetApiListCharactersResponseObject, error)

	// (POST /api/login)
	PostApiLogin(ctx context.Context, request PostApiLoginRequestObject) (PostApiLoginResponseObject, error)

	// (POST /api/new_character)
	PostApiNewCharacter(ctx context.Context, request PostApiNewCharacterRequestObject) (PostApiNewCharacterResponseObject, error)

	// (POST /api/new_item)
	PostApiNewItem(ctx context.Context, request PostApiNewItemRequestObject) (PostApiNewItemResponseObject, error)

	// (POST /api/new_spell)
	PostApiNewSpell(ctx context.Context, request PostApiNewSpellRequestObject) (PostApiNewSpellResponseObject, error)

	// (POST /api/register)
	PostApiRegister(ctx context.Context, request PostApiRegisterRequestObject) (PostApiRegisterResponseObject, error)

	// (POST /api/update_character)
	PostApiUpdateCharacter(ctx context.Context, request PostApiUpdateCharacterRequestObject) (PostApiUpdateCharacterResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostApiDeleteCharacter operation middleware
func (sh *strictHandler) PostApiDeleteCharacter(w http.ResponseWriter, r *http.Request) {
	var request PostApiDeleteCharacterRequestObject

	var body PostApiDeleteCharacterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiDeleteCharacter(ctx, request.(PostApiDeleteCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiDeleteCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiDeleteCharacterResponseObject); ok {
		if err := validResponse.VisitPostApiDeleteCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiDeleteItem operation middleware
func (sh *strictHandler) PostApiDeleteItem(w http.ResponseWriter, r *http.Request) {
	var request PostApiDeleteItemRequestObject

	var body PostApiDeleteItemJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiDeleteItem(ctx, request.(PostApiDeleteItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiDeleteItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiDeleteItemResponseObject); ok {
		if err := validResponse.VisitPostApiDeleteItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiDeleteSpell operation middleware
func (sh *strictHandler) PostApiDeleteSpell(w http.ResponseWriter, r *http.Request) {
	var request PostApiDeleteSpellRequestObject

	var body PostApiDeleteSpellJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiDeleteSpell(ctx, request.(PostApiDeleteSpellRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiDeleteSpell")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiDeleteSpellResponseObject); ok {
		if err := validResponse.VisitPostApiDeleteSpellResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiGetAllItems operation middleware
func (sh *strictHandler) GetApiGetAllItems(w http.ResponseWriter, r *http.Request) {
	var request GetApiGetAllItemsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiGetAllItems(ctx, request.(GetApiGetAllItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiGetAllItems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiGetAllItemsResponseObject); ok {
		if err := validResponse.VisitGetApiGetAllItemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiGetAllSpells operation middleware
func (sh *strictHandler) GetApiGetAllSpells(w http.ResponseWriter, r *http.Request) {
	var request GetApiGetAllSpellsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiGetAllSpells(ctx, request.(GetApiGetAllSpellsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiGetAllSpells")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiGetAllSpellsResponseObject); ok {
		if err := validResponse.VisitGetApiGetAllSpellsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiGetCharacter operation middleware
func (sh *strictHandler) GetApiGetCharacter(w http.ResponseWriter, r *http.Request, params GetApiGetCharacterParams) {
	var request GetApiGetCharacterRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiGetCharacter(ctx, request.(GetApiGetCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiGetCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiGetCharacterResponseObject); ok {
		if err := validResponse.VisitGetApiGetCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiListCharacters operation middleware
func (sh *strictHandler) GetApiListCharacters(w http.ResponseWriter, r *http.Request) {
	var request GetApiListCharactersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiListCharacters(ctx, request.(GetApiListCharactersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiListCharacters")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiListCharactersResponseObject); ok {
		if err := validResponse.VisitGetApiListCharactersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiLogin operation middleware
func (sh *strictHandler) PostApiLogin(w http.ResponseWriter, r *http.Request) {
	var request PostApiLoginRequestObject

	var body PostApiLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiLogin(ctx, request.(PostApiLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiLoginResponseObject); ok {
		if err := validResponse.VisitPostApiLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiNewCharacter operation middleware
func (sh *strictHandler) PostApiNewCharacter(w http.ResponseWriter, r *http.Request) {
	var request PostApiNewCharacterRequestObject

	var body PostApiNewCharacterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiNewCharacter(ctx, request.(PostApiNewCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiNewCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiNewCharacterResponseObject); ok {
		if err := validResponse.VisitPostApiNewCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiNewItem operation middleware
func (sh *strictHandler) PostApiNewItem(w http.ResponseWriter, r *http.Request) {
	var request PostApiNewItemRequestObject

	var body PostApiNewItemJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiNewItem(ctx, request.(PostApiNewItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiNewItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiNewItemResponseObject); ok {
		if err := validResponse.VisitPostApiNewItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiNewSpell operation middleware
func (sh *strictHandler) PostApiNewSpell(w http.ResponseWriter, r *http.Request) {
	var request PostApiNewSpellRequestObject

	var body PostApiNewSpellJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiNewSpell(ctx, request.(PostApiNewSpellRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiNewSpell")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiNewSpellResponseObject); ok {
		if err := validResponse.VisitPostApiNewSpellResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiRegister operation middleware
func (sh *strictHandler) PostApiRegister(w http.ResponseWriter, r *http.Request) {
	var request PostApiRegisterRequestObject

	var body PostApiRegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiRegister(ctx, request.(PostApiRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiRegisterResponseObject); ok {
		if err := validResponse.VisitPostApiRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiUpdateCharacter operation middleware
func (sh *strictHandler) PostApiUpdateCharacter(w http.ResponseWriter, r *http.Request) {
	var request PostApiUpdateCharacterRequestObject

	var body PostApiUpdateCharacterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiUpdateCharacter(ctx, request.(PostApiUpdateCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiUpdateCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiUpdateCharacterResponseObject); ok {
		if err := validResponse.VisitPostApiUpdateCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbW/bOBL+K4LugAMKbZO0u3d7+ZYmbZNDmhZxil1gURhjaSyxoUgtSdn1LvzfDyT1",
	"LsqW7XSve+svqiORw+G88ZkZ9nc/5GnGGTIl/fPffRkmmIL5eZmAgFCheD/7jKHSrzLBMxSKoBkAM0JJ",
	"+Uf7U5iA/ge/QJpR9M/PTgN/zkUKyj/3c8KUH/hqlaF/7hOmMEbhrwM/5GyPWRF+2WOWfr/7LKnEHrOW",
	"RO48ax34An/NicDIP//FLGwFZDdsidptBEbcnyoa3OprHfgQttf9YQy3EKOeVXyQShAWm/eUxCzFQm4s",
	"TzVft2/9wL/Tj0v9uL3zA/9BPy714/a1/qofl681gxUndrRjCVoYUP9TliEIYOEAcyLluZhmgs9JSJCF",
	"Kz2MKEzbovdvSZwo78IMd7FQvAAhYGUIKwXho2xRa9t6BGkhsvb7GWd5e/FR4o9I6CAGKc+7FjuG2gJo",
	"jg2FfR/8GJydBmcvghenwdnp6aetllesXJLqm1lnvOE/KHbvMkoGKbZ1cgWxXtmhDcYVygFNviEMpcQx",
	"SlR8mpDBCLZqGvTk4d4P/KvXP2ujfa+N+ObuwQ/8n24m+s31RWNP9YJ76bor6IKZYdl1JhhBVpsLSkMs",
	"peaSfVcwMwgfY8FzFjnsGmUoSKaIjcp93fT0+IbTR+8aBe/rxM16cwkXu5o9qbhYORmYcRbJoS+5nEKo",
	"CW9y3TmFhQ4bCr+okXt8BSIioUeYzIgAw7nDHrhKUEwjUNAgu1mNLV5aFMYoMoQMwtKUS2ZfjDx2KchN",
	"UqK4QLp7IOvL7h7YgJ/LfFZxUY9/SzlPpQL66JpVi1E2xGiZbVAcJT09cjpHULnAjQazfcjubjPJkNIQ",
	"pNIjnshzujscr4wB6yw3PkqcnEWk73v12jessFdQGI0J4BGCSqYSFi6wOQdCc9He3jg0l4chdoxuD2hW",
	"UAkqRlwyinCOLHRi5VwqnrYktVUeJE1zhrvNESiJVCWCGj9vkVOGAmZ0p3kdITUWr7hvkQ5KObiEhwzT",
	"IWCIX4wsZRcnFOf5RSj4DBQJtYIuGEmBetfAImqd7UKEwED/UAnFYtgVhpgVof2a2AMo8G+Y1NjR/FIk",
	"JVEZ/W/YAqUicfn3O4xISMwG74zX+IH/AUVN8wMKY2NWGh9QyByk/XSPlMT254Siwap87iXAtJtMFAJV",
	"if6ViwVZAHWCka4CcTUgujkQlbi/IKi2PP8ucO6f+387qfPFkyJZPHmDoN4PRoM5haV7/RhZhO2Eyn8H",
	"1AnpEiDCSSQxUnJ/ylzeJgR2kfS/xkSLhKipG5xTnO8BzVNo560vD8Xz27G8XjKw7A7j+T5n4+SjMM12",
	"ntZhsNROULBqaDZE7+KWRAjUbWCEEUVAkQVOUx61mPvuzF0VWCArAeco279RmA7bPgUW5xAP5jCXPE3d",
	"CLJHaT8QlnKGK4cXtDX17zGkcI858R5zsj3myJ3ndA1Pm5nUD9SPWD+ybGT++pBwQZh3IzibcxHjxky2",
	"nyuIGBj5DSrA1BuRoZCcQZmq9r+TUBUAqP+tqoiQ4wk55FyNslEvUIwKywLCjk1cA51/95rOXbagR0+V",
	"AKKeNpF4gyvvQoNMZdTxVRIJCQvC4qlKBF+acpvTpvarovTWQiZdiNnkxgMR9QrEo7cg2li8f57O1ZjY",
	"moGU+owghf3uXuGtKTQNfX86We0MBxaOu3sb4tW5dlGGcBqGTAjSCKOGbc44pwjMfCW/NWGKKdZpiyAp",
	"Ybk+kP3AfyBMm+kkBUqLoJCnfuDfgo2h17n55y3oAKly0PxccsqlHHBr+UjcriIzxI5Xj0sQdWYuB0Hk",
	"NOQsRKZEpe5NSMGk+TVUeGR8yab1CqPQRodGP8WDaPWkNN34rLPxzsKdvTmjCudUjqnW52pUgXeJkHE2",
	"hiBnsVxyEY2j2gsHP46ymy9Zx9h299siPJdHe3HEGNJ1kctWuJqtmVZJ12RApgvUcNfSG9pFlaDRzevh",
	"5lZFx3UENMob/cO0iuNdMNLK3etOS7d8W7mhs8vj1L3LwJpgvFfxa5/JZf5bZahFDl2EtSrnLDPoIjst",
	"ApDtoFXW04ZvVbpSlq/L/LjV4eqCwqozVpdCmsXxEl2WcL9RDm6mNC5HfC0EF/coM86kI7NNUUp3P7Cb",
	"WRYDXWs0ygP9JhkynBc4aATCuaAonEd6JtCwI0kBsxsVhVwqL4EFelevf9ZY8eylx4WXkDgZX/9s0w9q",
	"vl0bbuSE/aODyz1qBQOdhMCEuKl9Wx+2PxmPMNi9aHNeCIVzCJU5QZkCwszW33dO902if+AiTFyid0TJ",
	"s+et5HROOTT2xfJ0Nhzx6h0FVlgNTxpsh9xjTKRCgdFHiWKiRF5lRG3xK/6IboyQSxT9XX/mCYs4nr14",
	"udVSKgJBsYqL0eZh67CN5lWMjieCQkGAbpvVxz4KVC5dKK13xcAMDJoEncCPpzpbdOO+BYqZZXLLasXA",
	"mlxQb9G1ag9q9dfeljBFeT27k2rlPbpN5yu+9vzshkkFxmOvYKUl906DWxMfrnku9L8fmSLUi4g5wjBy",
	"+Fq3fZ5XoKq9rrMuPp9vuJnzBH3tp72M0O+S/2/uMGy6nRClcaXnfq+hkncp1ndIURM03TSNda7RWPUE",
	"TIozFGA7/BV0g8YdgIqPQgkuXvs1wdP9GrPvIEZT83FXK1i80QgcKwwWuwyxniM98NycLRM0BZN3hBon",
	"eoOoTE1qtV2EDcJBre/hmxCCqNwdqAJfhgnntFupZZ/z4Ya/0jmrwxPLPHhE+dxQqEVTr0xE6OqJdATQ",
	"nF8AVWfmRVKcKj4NQaqn8+xhhev12tXGQoSvtAt61Z/3CNVPnbzI7SqvtGzW2KTsPHNv909316rcSs+D",
	"bouM8BKYEiTbLrwmncEQ40ZohXs00tAaMHQMrHKMMowEzQOuCnuFfrqnfOWl28uUW2BfBtJm/S3Pevbs",
	"2TOXMz8lFKxWdkpXYpgLolaTMMHUsvqfpXqFIGyBc2Z+vSlN7/NSWfljakKWHVcRTpTK/PXa9LHmvFdD",
	"9q/YlfcKwke0gZ4oWzFtvV2gkHb02fPT56emQZEhg4z45/7L52fPT82mVGKYPYGMnERIUeE0LO8LG4EX",
	"aU6HATPSA68ea8hbfd9E/rn/gUt1kRE78rIxTMsXpXrFo5VFvUwVfVzIMkpCQ+Lks7Qozha3+oZAIteJ",
	"1VEfcWqrizD9myudTVZb8RT3rCiK2xYmpzarvjg9PYDnlmA3VfK6N7ZNc3TcfoPGKmP2PrGXXuY5pati",
	"15GnEmxodh343x+0bzfvQbMo0TglgTGuvDlhUUMlS6ISj0TeD1tdtiQajNX+K4i8wiY9MvdCYP/oLm9F",
	"cLaTCDbpt12scfD0kUGuEi6IxEgv/sOO8j9o8QlP0UM9qhXa/PNfWkHtF1/z6H9aayFDbO7uVYYr/U96",
	"bjOsEIXp9ojCPDNuYzS5sSO+1UCiN/DVYsiQL5XSHXvFwRU5DI2DgoahcHSWcc7yURHq8BNTYRhx9Npx",
	"Gx1lUgz5Vj3FbOEPd5VKwKObaS5nsVQO8hZL4ugu+7mLTpKB0mnVHCzy9vaCb1F5QKkHCyAUZtTGKOkR",
	"5oFHiUlW2h70FrUD6SelN4b2gVZ58PWzvhhviVTlUSOPFnSgBdV99pEmZCeMtKFJ2fT8+ka0+QbAoBUV",
	"+z+a0f5m1ErtBq2ozmdmK8+cIgNm08yXMxCQosHUmjmiif2ao20Xm+KGPZDqE0qJHIOGoHpH9qcDjXGn",
	"3LUv+3tUuWDHDPOYYT5RhqljcO2Cw5HcBDwdyuuxpvJjL0N5uXTUsaxP6pmNpZ8qmHfqQ/3/OXdJUZie",
	"av9K/IDJV72kffpH1Ra9M+fljA33k/s3Z52XZl1QeuiKVHkrym5p+6XWvqHV+zHH9NHJDnEyHttbme68",
	"9FZ/9ghT3IMwLNofztzUjDwgK90klXb7YL1er7/iUTd0WWVjDugJM6vojDyxRW7l4yfBWeyVbY2Tqqnx",
	"7RhnwwwvrGGWBshwOaY3cSkQTIGE4XJ7f+IOl0/RnDgQEd21WP2LdR3yLIKBrsMxVu8Xq7WrbK63t7xk",
	"U8n9DpcH1ttHl6TX/++l8tAIPaq6HEcb3y/j1ua9pUzesu+NpfI7XB5aJx9fSF7/BUrclZUfC9wHWbko",
	"4OWwkZcA1J25FvZdDjoi7hpxn/5xiLtT/Cmht0ekB9T8dyv97s+BwC1SGwPCP5qRzTs1Cahqw/iFSHPH",
	"zGmwdu7TXxn6FoGwBv5cVBD46XKAAxOSsQD9WLQ9nmy75ihmsliUDY1cUP/cVzzifmNON6DoSIRMFXur",
	"Wx8mQq2DHvy7/3jlzbloVHrrOQ12+jPNTX/PXoysZtijef1p/d8AAAD//5YWV6NnVQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
