// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	JwtBearerScopes = "JwtBearer.Scopes"
)

// Defines values for CharacterObjectAlignment.
const (
	CE CharacterObjectAlignment = "CE"
	CG CharacterObjectAlignment = "CG"
	CN CharacterObjectAlignment = "CN"
	LE CharacterObjectAlignment = "LE"
	LG CharacterObjectAlignment = "LG"
	LN CharacterObjectAlignment = "LN"
	NE CharacterObjectAlignment = "NE"
	NG CharacterObjectAlignment = "NG"
	TN CharacterObjectAlignment = "TN"
)

// Valid indicates whether the value is a known member of the CharacterObjectAlignment enum.
func (e CharacterObjectAlignment) Valid() bool {
	switch e {
	case CE:
		return true
	case CG:
		return true
	case CN:
		return true
	case LE:
		return true
	case LG:
		return true
	case LN:
		return true
	case NE:
		return true
	case NG:
		return true
	case TN:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectAttacksDamageDiceValue.
const (
	CharacterObjectAttacksDamageDiceValueN10  CharacterObjectAttacksDamageDiceValue = 10
	CharacterObjectAttacksDamageDiceValueN100 CharacterObjectAttacksDamageDiceValue = 100
	CharacterObjectAttacksDamageDiceValueN12  CharacterObjectAttacksDamageDiceValue = 12
	CharacterObjectAttacksDamageDiceValueN20  CharacterObjectAttacksDamageDiceValue = 20
	CharacterObjectAttacksDamageDiceValueN4   CharacterObjectAttacksDamageDiceValue = 4
	CharacterObjectAttacksDamageDiceValueN8   CharacterObjectAttacksDamageDiceValue = 8
)

// Valid indicates whether the value is a known member of the CharacterObjectAttacksDamageDiceValue enum.
func (e CharacterObjectAttacksDamageDiceValue) Valid() bool {
	switch e {
	case CharacterObjectAttacksDamageDiceValueN10:
		return true
	case CharacterObjectAttacksDamageDiceValueN100:
		return true
	case CharacterObjectAttacksDamageDiceValueN12:
		return true
	case CharacterObjectAttacksDamageDiceValueN20:
		return true
	case CharacterObjectAttacksDamageDiceValueN4:
		return true
	case CharacterObjectAttacksDamageDiceValueN8:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectAttacksToHitAbility.
const (
	CharacterObjectAttacksToHitAbilityCHA CharacterObjectAttacksToHitAbility = "CHA"
	CharacterObjectAttacksToHitAbilityCON CharacterObjectAttacksToHitAbility = "CON"
	CharacterObjectAttacksToHitAbilityDEX CharacterObjectAttacksToHitAbility = "DEX"
	CharacterObjectAttacksToHitAbilityINT CharacterObjectAttacksToHitAbility = "INT"
	CharacterObjectAttacksToHitAbilitySTR CharacterObjectAttacksToHitAbility = "STR"
	CharacterObjectAttacksToHitAbilityWIS CharacterObjectAttacksToHitAbility = "WIS"
)

// Valid indicates whether the value is a known member of the CharacterObjectAttacksToHitAbility enum.
func (e CharacterObjectAttacksToHitAbility) Valid() bool {
	switch e {
	case CharacterObjectAttacksToHitAbilityCHA:
		return true
	case CharacterObjectAttacksToHitAbilityCON:
		return true
	case CharacterObjectAttacksToHitAbilityDEX:
		return true
	case CharacterObjectAttacksToHitAbilityINT:
		return true
	case CharacterObjectAttacksToHitAbilitySTR:
		return true
	case CharacterObjectAttacksToHitAbilityWIS:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectExpertises.
const (
	CharacterObjectExpertisesAcrobatics     CharacterObjectExpertises = "Acrobatics"
	CharacterObjectExpertisesAnimalHandling CharacterObjectExpertises = "Animal Handling"
	CharacterObjectExpertisesArcana         CharacterObjectExpertises = "Arcana"
	CharacterObjectExpertisesAthletics      CharacterObjectExpertises = "Athletics"
	CharacterObjectExpertisesDeception      CharacterObjectExpertises = "Deception"
	CharacterObjectExpertisesHistory        CharacterObjectExpertises = "History"
	CharacterObjectExpertisesInsight        CharacterObjectExpertises = "Insight"
	CharacterObjectExpertisesIntimidation   CharacterObjectExpertises = "Intimidation"
	CharacterObjectExpertisesInvestigation  CharacterObjectExpertises = "Investigation"
	CharacterObjectExpertisesMedicine       CharacterObjectExpertises = "Medicine"
	CharacterObjectExpertisesNature         CharacterObjectExpertises = "Nature"
	CharacterObjectExpertisesPerception     CharacterObjectExpertises = "Perception"
	CharacterObjectExpertisesPerformance    CharacterObjectExpertises = "Performance"
	CharacterObjectExpertisesPersuasion     CharacterObjectExpertises = "Persuasion"
	CharacterObjectExpertisesReligion       CharacterObjectExpertises = "Religion"
	CharacterObjectExpertisesSleightOfHand  CharacterObjectExpertises = "Sleight of hand"
	CharacterObjectExpertisesStealth        CharacterObjectExpertises = "Stealth"
	CharacterObjectExpertisesSurvival       CharacterObjectExpertises = "Survival"
)

// Valid indicates whether the value is a known member of the CharacterObjectExpertises enum.
func (e CharacterObjectExpertises) Valid() bool {
	switch e {
	case CharacterObjectExpertisesAcrobatics:
		return true
	case CharacterObjectExpertisesAnimalHandling:
		return true
	case CharacterObjectExpertisesArcana:
		return true
	case CharacterObjectExpertisesAthletics:
		return true
	case CharacterObjectExpertisesDeception:
		return true
	case CharacterObjectExpertisesHistory:
		return true
	case CharacterObjectExpertisesInsight:
		return true
	case CharacterObjectExpertisesIntimidation:
		return true
	case CharacterObjectExpertisesInvestigation:
		return true
	case CharacterObjectExpertisesMedicine:
		return true
	case CharacterObjectExpertisesNature:
		return true
	case CharacterObjectExpertisesPerception:
		return true
	case CharacterObjectExpertisesPerformance:
		return true
	case CharacterObjectExpertisesPersuasion:
		return true
	case CharacterObjectExpertisesReligion:
		return true
	case CharacterObjectExpertisesSleightOfHand:
		return true
	case CharacterObjectExpertisesStealth:
		return true
	case CharacterObjectExpertisesSurvival:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectHpHitDiceValue.
const (
	CharacterObjectHpHitDiceValueN10 CharacterObjectHpHitDiceValue = 10
	CharacterObjectHpHitDiceValueN12 CharacterObjectHpHitDiceValue = 12
	CharacterObjectHpHitDiceValueN20 CharacterObjectHpHitDiceValue = 20
	CharacterObjectHpHitDiceValueN4  CharacterObjectHpHitDiceValue = 4
	CharacterObjectHpHitDiceValueN8  CharacterObjectHpHitDiceValue = 8
)

// Valid indicates whether the value is a known member of the CharacterObjectHpHitDiceValue enum.
func (e CharacterObjectHpHitDiceValue) Valid() bool {
	switch e {
	case CharacterObjectHpHitDiceValueN10:
		return true
	case CharacterObjectHpHitDiceValueN12:
		return true
	case CharacterObjectHpHitDiceValueN20:
		return true
	case CharacterObjectHpHitDiceValueN4:
		return true
	case CharacterObjectHpHitDiceValueN8:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectProficiencies.
const (
	CharacterObjectProficienciesAcrobatics     CharacterObjectProficiencies = "Acrobatics"
	CharacterObjectProficienciesAnimalHandling CharacterObjectProficiencies = "Animal Handling"
	CharacterObjectProficienciesArcana         CharacterObjectProficiencies = "Arcana"
	CharacterObjectProficienciesAthletics      CharacterObjectProficiencies = "Athletics"
	CharacterObjectProficienciesDeception      CharacterObjectProficiencies = "Deception"
	CharacterObjectProficienciesHistory        CharacterObjectProficiencies = "History"
	CharacterObjectProficienciesInsight        CharacterObjectProficiencies = "Insight"
	CharacterObjectProficienciesIntimidation   CharacterObjectProficiencies = "Intimidation"
	CharacterObjectProficienciesInvestigation  CharacterObjectProficiencies = "Investigation"
	CharacterObjectProficienciesMedicine       CharacterObjectProficiencies = "Medicine"
	CharacterObjectProficienciesNature         CharacterObjectProficiencies = "Nature"
	CharacterObjectProficienciesPerception     CharacterObjectProficiencies = "Perception"
	CharacterObjectProficienciesPerformance    CharacterObjectProficiencies = "Performance"
	CharacterObjectProficienciesPersuasion     CharacterObjectProficiencies = "Persuasion"
	CharacterObjectProficienciesReligion       CharacterObjectProficiencies = "Religion"
	CharacterObjectProficienciesSleightOfHand  CharacterObjectProficiencies = "Sleight of hand"
	CharacterObjectProficienciesStealth        CharacterObjectProficiencies = "Stealth"
	CharacterObjectProficienciesSurvival       CharacterObjectProficiencies = "Survival"
)

// Valid indicates whether the value is a known member of the CharacterObjectProficiencies enum.
func (e CharacterObjectProficiencies) Valid() bool {
	switch e {
	case CharacterObjectProficienciesAcrobatics:
		return true
	case CharacterObjectProficienciesAnimalHandling:
		return true
	case CharacterObjectProficienciesArcana:
		return true
	case CharacterObjectProficienciesAthletics:
		return true
	case CharacterObjectProficienciesDeception:
		return true
	case CharacterObjectProficienciesHistory:
		return true
	case CharacterObjectProficienciesInsight:
		return true
	case CharacterObjectProficienciesIntimidation:
		return true
	case CharacterObjectProficienciesInvestigation:
		return true
	case CharacterObjectProficienciesMedicine:
		return true
	case CharacterObjectProficienciesNature:
		return true
	case CharacterObjectProficienciesPerception:
		return true
	case CharacterObjectProficienciesPerformance:
		return true
	case CharacterObjectProficienciesPersuasion:
		return true
	case CharacterObjectProficienciesReligion:
		return true
	case CharacterObjectProficienciesSleightOfHand:
		return true
	case CharacterObjectProficienciesStealth:
		return true
	case CharacterObjectProficienciesSurvival:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectSavingThrowProf.
const (
	CharacterObjectSavingThrowProfCHA CharacterObjectSavingThrowProf = "CHA"
	CharacterObjectSavingThrowProfCON CharacterObjectSavingThrowProf = "CON"
	CharacterObjectSavingThrowProfDEX CharacterObjectSavingThrowProf = "DEX"
	CharacterObjectSavingThrowProfINT CharacterObjectSavingThrowProf = "INT"
	CharacterObjectSavingThrowProfSTR CharacterObjectSavingThrowProf = "STR"
	CharacterObjectSavingThrowProfWIS CharacterObjectSavingThrowProf = "WIS"
)

// Valid indicates whether the value is a known member of the CharacterObjectSavingThrowProf enum.
func (e CharacterObjectSavingThrowProf) Valid() bool {
	switch e {
	case CharacterObjectSavingThrowProfCHA:
		return true
	case CharacterObjectSavingThrowProfCON:
		return true
	case CharacterObjectSavingThrowProfDEX:
		return true
	case CharacterObjectSavingThrowProfINT:
		return true
	case CharacterObjectSavingThrowProfSTR:
		return true
	case CharacterObjectSavingThrowProfWIS:
		return true
	default:
		return false
	}
}

// Defines values for CharacterObjectSize.
const (
	Colossal   CharacterObjectSize = "Colossal"
	Diminutive CharacterObjectSize = "Diminutive"
	Fine       CharacterObjectSize = "Fine"
	Gargantuan CharacterObjectSize = "Gargantuan"
	Huge       CharacterObjectSize = "Huge"
	Large      CharacterObjectSize = "Large"
	Medium     CharacterObjectSize = "Medium"
	Small      CharacterObjectSize = "Small"
	Tiny       CharacterObjectSize = "Tiny"
)

// Valid indicates whether the value is a known member of the CharacterObjectSize enum.
func (e CharacterObjectSize) Valid() bool {
	switch e {
	case Colossal:
		return true
	case Diminutive:
		return true
	case Fine:
		return true
	case Gargantuan:
		return true
	case Huge:
		return true
	case Large:
		return true
	case Medium:
		return true
	case Small:
		return true
	case Tiny:
		return true
	default:
		return false
	}
}

// Defines values for ItemObjectItemType.
const (
	ItemObjectItemTypeArmour    ItemObjectItemType = "Armour"
	ItemObjectItemTypeArtefact  ItemObjectItemType = "Artefact"
	ItemObjectItemTypeContainer ItemObjectItemType = "Container"
	ItemObjectItemTypeOther     ItemObjectItemType = "Other"
	ItemObjectItemTypeWeapon    ItemObjectItemType = "Weapon"
)

// Valid indicates whether the value is a known member of the ItemObjectItemType enum.
func (e ItemObjectItemType) Valid() bool {
	switch e {
	case ItemObjectItemTypeArmour:
		return true
	case ItemObjectItemTypeArtefact:
		return true
	case ItemObjectItemTypeContainer:
		return true
	case ItemObjectItemTypeOther:
		return true
	case ItemObjectItemTypeWeapon:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectDurationDurationType.
const (
	Days           SpellObjectDurationDurationType = "Days"
	Hours          SpellObjectDurationDurationType = "Hours"
	Instant        SpellObjectDurationDurationType = "Instant"
	Minutes        SpellObjectDurationDurationType = "Minutes"
	UntilDispelled SpellObjectDurationDurationType = "Until dispelled"
)

// Valid indicates whether the value is a known member of the SpellObjectDurationDurationType enum.
func (e SpellObjectDurationDurationType) Valid() bool {
	switch e {
	case Days:
		return true
	case Hours:
		return true
	case Instant:
		return true
	case Minutes:
		return true
	case UntilDispelled:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectEffectAbility.
const (
	CHA SpellObjectEffectAbility = "CHA"
	CON SpellObjectEffectAbility = "CON"
	DEX SpellObjectEffectAbility = "DEX"
	INT SpellObjectEffectAbility = "INT"
	STR SpellObjectEffectAbility = "STR"
	WIS SpellObjectEffectAbility = "WIS"
)

// Valid indicates whether the value is a known member of the SpellObjectEffectAbility enum.
func (e SpellObjectEffectAbility) Valid() bool {
	switch e {
	case CHA:
		return true
	case CON:
		return true
	case DEX:
		return true
	case INT:
		return true
	case STR:
		return true
	case WIS:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectEffectDiceValue.
const (
	SpellObjectEffectDiceValueN10  SpellObjectEffectDiceValue = 10
	SpellObjectEffectDiceValueN100 SpellObjectEffectDiceValue = 100
	SpellObjectEffectDiceValueN12  SpellObjectEffectDiceValue = 12
	SpellObjectEffectDiceValueN20  SpellObjectEffectDiceValue = 20
	SpellObjectEffectDiceValueN4   SpellObjectEffectDiceValue = 4
	SpellObjectEffectDiceValueN8   SpellObjectEffectDiceValue = 8
)

// Valid indicates whether the value is a known member of the SpellObjectEffectDiceValue enum.
func (e SpellObjectEffectDiceValue) Valid() bool {
	switch e {
	case SpellObjectEffectDiceValueN10:
		return true
	case SpellObjectEffectDiceValueN100:
		return true
	case SpellObjectEffectDiceValueN12:
		return true
	case SpellObjectEffectDiceValueN20:
		return true
	case SpellObjectEffectDiceValueN4:
		return true
	case SpellObjectEffectDiceValueN8:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectEffectEffect.
const (
	SpellObjectEffectEffectHeal   SpellObjectEffectEffect = "Heal"
	SpellObjectEffectEffectMelee  SpellObjectEffectEffect = "Melee"
	SpellObjectEffectEffectOther  SpellObjectEffectEffect = "Other"
	SpellObjectEffectEffectRanged SpellObjectEffectEffect = "Ranged"
	SpellObjectEffectEffectSave   SpellObjectEffectEffect = "Save"
)

// Valid indicates whether the value is a known member of the SpellObjectEffectEffect enum.
func (e SpellObjectEffectEffect) Valid() bool {
	switch e {
	case SpellObjectEffectEffectHeal:
		return true
	case SpellObjectEffectEffectMelee:
		return true
	case SpellObjectEffectEffectOther:
		return true
	case SpellObjectEffectEffectRanged:
		return true
	case SpellObjectEffectEffectSave:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectRangeRangeType.
const (
	Any   SpellObjectRangeRangeType = "Any"
	Feet  SpellObjectRangeRangeType = "Feet"
	Miles SpellObjectRangeRangeType = "Miles"
	Self  SpellObjectRangeRangeType = "Self"
	Touch SpellObjectRangeRangeType = "Touch"
)

// Valid indicates whether the value is a known member of the SpellObjectRangeRangeType enum.
func (e SpellObjectRangeRangeType) Valid() bool {
	switch e {
	case Any:
		return true
	case Feet:
		return true
	case Miles:
		return true
	case Self:
		return true
	case Touch:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectTimeToCastTime.
const (
	Action      SpellObjectTimeToCastTime = "Action"
	BonusAction SpellObjectTimeToCastTime = "Bonus Action"
	Reaction    SpellObjectTimeToCastTime = "Reaction"
	Rounds      SpellObjectTimeToCastTime = "Rounds"
)

// Valid indicates whether the value is a known member of the SpellObjectTimeToCastTime enum.
func (e SpellObjectTimeToCastTime) Valid() bool {
	switch e {
	case Action:
		return true
	case BonusAction:
		return true
	case Reaction:
		return true
	case Rounds:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectUpcastDiceValue.
const (
	SpellObjectUpcastDiceValueN10  SpellObjectUpcastDiceValue = 10
	SpellObjectUpcastDiceValueN100 SpellObjectUpcastDiceValue = 100
	SpellObjectUpcastDiceValueN12  SpellObjectUpcastDiceValue = 12
	SpellObjectUpcastDiceValueN20  SpellObjectUpcastDiceValue = 20
	SpellObjectUpcastDiceValueN4   SpellObjectUpcastDiceValue = 4
	SpellObjectUpcastDiceValueN8   SpellObjectUpcastDiceValue = 8
)

// Valid indicates whether the value is a known member of the SpellObjectUpcastDiceValue enum.
func (e SpellObjectUpcastDiceValue) Valid() bool {
	switch e {
	case SpellObjectUpcastDiceValueN10:
		return true
	case SpellObjectUpcastDiceValueN100:
		return true
	case SpellObjectUpcastDiceValueN12:
		return true
	case SpellObjectUpcastDiceValueN20:
		return true
	case SpellObjectUpcastDiceValueN4:
		return true
	case SpellObjectUpcastDiceValueN8:
		return true
	default:
		return false
	}
}

// Defines values for SpellObjectUpcastUpcastType.
const (
	Cantrip SpellObjectUpcastUpcastType = "Cantrip"
	Level   SpellObjectUpcastUpcastType = "Level"
)

// Valid indicates whether the value is a known member of the SpellObjectUpcastUpcastType enum.
func (e SpellObjectUpcastUpcastType) Valid() bool {
	switch e {
	case Cantrip:
		return true
	case Level:
		return true
	default:
		return false
	}
}

// CharacterObject defines model for CharacterObject.
type CharacterObject struct {
	Abilities *struct {
		Cha *uint `json:"cha,omitempty"`
		Con *uint `json:"con,omitempty"`
		Dex *uint `json:"dex,omitempty"`
		Int *uint `json:"int,omitempty"`
		Str *uint `json:"str,omitempty"`
		Wis *uint `json:"wis,omitempty"`
	} `json:"abilities,omitempty"`
	Ac                *uint                     `json:"ac,omitempty"`
	Age               *string                   `json:"age,omitempty"`
	Alignment         *CharacterObjectAlignment `json:"alignment,omitempty"`
	Allies            *string                   `json:"allies,omitempty"`
	Appearance        *string                   `json:"appearance,omitempty"`
	ArmourProficiency *[]string                 `json:"armour_proficiency,omitempty"`
	Attacks           *[]struct {
		Damage *struct {
			Bonus *uint `json:"bonus,omitempty"`
			Dice  *struct {
				Amount *uint                                  `json:"amount,omitempty"`
				Value  *CharacterObjectAttacksDamageDiceValue `json:"value,omitempty"`
			} `json:"dice,omitempty"`
		} `json:"damage,omitempty"`
		Name  *string   `json:"name,omitempty"`
		Notes *[]string `json:"notes,omitempty"`
		ToHit *struct {
			Ability *CharacterObjectAttacksToHitAbility `json:"ability,omitempty"`
			Bonus   *uint                               `json:"bonus,omitempty"`
		} `json:"to_hit,omitempty"`
	} `json:"attacks,omitempty"`
	Background *struct {
		Description *string `json:"description,omitempty"`
		Name        *string `json:"name,omitempty"`
	} `json:"background,omitempty"`
	Backstory    *string `json:"backstory,omitempty"`
	Bonds        *string `json:"bonds,omitempty"`
	BonusActions *[]struct {
		FlavourText *string                 `json:"flavour_text,omitempty"`
		Name        *string                 `json:"name,omitempty"`
		OtherData   *map[string]interface{} `json:"other_data,omitempty"`
	} `json:"bonus_actions,omitempty"`
	Capacity *uint `json:"capacity,omitempty"`
	Class    *[]struct {
		Level    *uint   `json:"level,omitempty"`
		Name     *string `json:"name,omitempty"`
		Subclass *string `json:"subclass,omitempty"`
	} `json:"class,omitempty"`
	ClassFeatures *[]struct {
		Features *[]struct {
			Description *string `json:"description,omitempty"`
			Name        *string `json:"name,omitempty"`
		} `json:"features,omitempty"`
		Name *string `json:"name,omitempty"`
	} `json:"class_features,omitempty"`
	Conditions *[]string `json:"conditions,omitempty"`
	DeathSaves *struct {
		Failure *uint `json:"failure,omitempty"`
		Success *uint `json:"success,omitempty"`
	} `json:"death_saves,omitempty"`
	Defences *struct {
		Custom     *[]string `json:"custom,omitempty"`
		Immune     *[]string `json:"immune,omitempty"`
		Resistance *[]string `json:"resistance,omitempty"`
		Vulnerable *[]string `json:"vulnerable,omitempty"`
	} `json:"defences,omitempty"`
	Enemies    *string                      `json:"enemies,omitempty"`
	Expertises *[]CharacterObjectExpertises `json:"expertises,omitempty"`
	Eyes       *string                      `json:"eyes,omitempty"`
	Faith      *string                      `json:"faith,omitempty"`
	Feats      *[]FeatObject                `json:"feats,omitempty"`
	Flaws      *string                      `json:"flaws,omitempty"`
	Gender     *string                      `json:"gender,omitempty"`
	Hair       *string                      `json:"hair,omitempty"`
	Height     *string                      `json:"height,omitempty"`
	Hp         *struct {
		Current *uint `json:"current,omitempty"`
		HitDice *struct {
			Left  *uint                          `json:"left,omitempty"`
			Max   *uint                          `json:"max,omitempty"`
			Value *CharacterObjectHpHitDiceValue `json:"value,omitempty"`
		} `json:"hit_dice,omitempty"`
		Max  *uint `json:"max,omitempty"`
		Temp *uint `json:"temp,omitempty"`
	} `json:"hp,omitempty"`
	Ideals        *string       `json:"ideals,omitempty"`
	InitiativeMod *int          `json:"initiative_mod,omitempty"`
	Inventory     *[]ItemObject `json:"inventory,omitempty"`
	Languages     *[]string     `json:"languages,omitempty"`
	Level         *uint         `json:"level,omitempty"`
	Money         *struct {
		Cp *uint `json:"cp,omitempty"`
		Ep *uint `json:"ep,omitempty"`
		Gp *uint `json:"gp,omitempty"`
		Pp *uint `json:"pp,omitempty"`
		Sp *uint `json:"sp,omitempty"`
	} `json:"money,omitempty"`
	Name           *string                         `json:"name,omitempty"`
	Notes          *string                         `json:"notes,omitempty"`
	Organizations  *string                         `json:"organizations,omitempty"`
	Personality    *string                         `json:"personality,omitempty"`
	Picture        *string                         `json:"picture,omitempty"`
	Proficiencies  *[]CharacterObjectProficiencies `json:"proficiencies,omitempty"`
	ProficiencyMod *uint                           `json:"proficiency_mod,omitempty"`
	Race           *string                         `json:"race,omitempty"`
	RaceTraits     *[]struct {
		Description *string `json:"description,omitempty"`
		Name        *string `json:"name,omitempty"`
	} `json:"race_traits,omitempty"`
	SavingThrowProf *[]CharacterObjectSavingThrowProf `json:"saving_throw_prof,omitempty"`
	Senses          *struct {
		Other                *[]string `json:"other,omitempty"`
		PassiveInsight       *uint     `json:"passive_insight,omitempty"`
		PassiveInvestigation *uint     `json:"passive_investigation,omitempty"`
		PassivePerception    *uint     `json:"passive_perception,omitempty"`
	} `json:"senses,omitempty"`
	Shielded *bool                `json:"shielded,omitempty"`
	Size     *CharacterObjectSize `json:"size,omitempty"`
	Skin     *string              `json:"skin,omitempty"`
	Speed    *uint                `json:"speed,omitempty"`
	Spells   *struct {
		CurrentConcentration *SpellObject   `json:"current_concentration,omitempty"`
		KnownSpells          *[]SpellObject `json:"known_spells,omitempty"`
		ReadySpells          *[]SpellObject `json:"ready_spells,omitempty"`
	} `json:"spells,omitempty"`
	ToolsProficiency  *[]string `json:"tools_proficiency,omitempty"`
	WeaponProficiency *[]string `json:"weapon_proficiency,omitempty"`
	Weight            *uint     `json:"weight,omitempty"`
	Xp                *uint     `json:"xp,omitempty"`
}

// CharacterObjectAlignment defines model for CharacterObject.Alignment.
type CharacterObjectAlignment string

// CharacterObjectAttacksDamageDiceValue defines model for CharacterObject.Attacks.Damage.Dice.Value.
type CharacterObjectAttacksDamageDiceValue int

// CharacterObjectAttacksToHitAbility defines model for CharacterObject.Attacks.ToHit.Ability.
type CharacterObjectAttacksToHitAbility string

// CharacterObjectExpertises defines model for CharacterObject.Expertises.
type CharacterObjectExpertises string

// CharacterObjectHpHitDiceValue defines model for CharacterObject.Hp.HitDice.Value.
type CharacterObjectHpHitDiceValue int

// CharacterObjectProficiencies defines model for CharacterObject.Proficiencies.
type CharacterObjectProficiencies string

// CharacterObjectSavingThrowProf defines model for CharacterObject.SavingThrowProf.
type CharacterObjectSavingThrowProf string

// CharacterObjectSize defines model for CharacterObject.Size.
type CharacterObjectSize string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message *string `json:"message,omitempty"`
}

// FeatObject defines model for FeatObject.
type FeatObject struct {
	Benefits      *string `json:"benefits,omitempty"`
	Name          *string `json:"name,omitempty"`
	Prerequisites *string `json:"prerequisites,omitempty"`
}

// ItemObject defines model for ItemObject.
type ItemObject struct {
	Cost     *uint                   `json:"cost,omitempty"`
	Data     *map[string]interface{} `json:"data,omitempty"`
	ItemType *ItemObjectItemType     `json:"item_type,omitempty"`
	Name     *string                 `json:"name,omitempty"`
	Weight   *float32                `json:"weight,omitempty"`
}

// ItemObjectItemType defines model for ItemObject.ItemType.
type ItemObjectItemType string

// RegisteredUserStructure defines model for RegisteredUserStructure.
type RegisteredUserStructure struct {
	CreatedAt *string `json:"CreatedAt,omitempty"`
	DeletedAt *string `json:"DeletedAt,omitempty"`
	ID        *int    `json:"ID,omitempty"`
	UpdatedAt *string `json:"UpdatedAt,omitempty"`
	Password  *string `json:"password,omitempty"`
	Token     *string `json:"token,omitempty"`
	Username  *string `json:"username,omitempty"`
}

// SpellObject defines model for SpellObject.
type SpellObject struct {
	Components *struct {
		Material *struct {
			Components *string `json:"components,omitempty"`
			Status     *bool   `json:"status,omitempty"`
		} `json:"material,omitempty"`
		Somatic *bool `json:"somatic,omitempty"`
		Verbal  *bool `json:"verbal,omitempty"`
	} `json:"components,omitempty"`
	Concentration *bool   `json:"concentration,omitempty"`
	Description   *string `json:"description,omitempty"`
	Duration      *struct {
		Duration     *int                             `json:"duration,omitempty"`
		DurationType *SpellObjectDurationDurationType `json:"duration_type,omitempty"`
	} `json:"duration,omitempty"`
	Effect *struct {
		Ability *SpellObjectEffectAbility `json:"ability,omitempty"`
		Dice    *struct {
			Amount *uint                       `json:"amount,omitempty"`
			Bonus  *uint                       `json:"bonus,omitempty"`
			Value  *SpellObjectEffectDiceValue `json:"value,omitempty"`
		} `json:"dice,omitempty"`
		DmgType *string                  `json:"dmg_type,omitempty"`
		Effect  *SpellObjectEffectEffect `json:"effect,omitempty"`
	} `json:"effect,omitempty"`
	Level *uint   `json:"level,omitempty"`
	Name  *string `json:"name,omitempty"`
	Range *struct {
		Amount    *int                       `json:"amount,omitempty"`
		Notes     *string                    `json:"notes,omitempty"`
		RangeType *SpellObjectRangeRangeType `json:"range_type,omitempty"`
	} `json:"range,omitempty"`
	Ritual *bool   `json:"ritual,omitempty"`
	School *string `json:"school,omitempty"`
	Target *struct {
		Size       *uint   `json:"size,omitempty"`
		TargetType *string `json:"target_type,omitempty"`
	} `json:"target,omitempty"`
	TimeToCast *struct {
		Amount *uint                      `json:"amount,omitempty"`
		Notes  *string                    `json:"notes,omitempty"`
		Time   *SpellObjectTimeToCastTime `json:"time,omitempty"`
	} `json:"time_to_cast,omitempty"`
	Upcast *struct {
		Dice *struct {
			Amount *uint                       `json:"amount,omitempty"`
			Value  *SpellObjectUpcastDiceValue `json:"value,omitempty"`
		} `json:"dice,omitempty"`
		UpcastType *SpellObjectUpcastUpcastType `json:"upcast_type,omitempty"`
	} `json:"upcast,omitempty"`
}

// SpellObjectDurationDurationType defines model for SpellObject.Duration.DurationType.
type SpellObjectDurationDurationType string

// SpellObjectEffectAbility defines model for SpellObject.Effect.Ability.
type SpellObjectEffectAbility string

// SpellObjectEffectDiceValue defines model for SpellObject.Effect.Dice.Value.
type SpellObjectEffectDiceValue int

// SpellObjectEffectEffect defines model for SpellObject.Effect.Effect.
type SpellObjectEffectEffect string

// SpellObjectRangeRangeType defines model for SpellObject.Range.RangeType.
type SpellObjectRangeRangeType string

// SpellObjectTimeToCastTime defines model for SpellObject.TimeToCast.Time.
type SpellObjectTimeToCastTime string

// SpellObjectUpcastDiceValue defines model for SpellObject.Upcast.Dice.Value.
type SpellObjectUpcastDiceValue int

// SpellObjectUpcastUpcastType defines model for SpellObject.Upcast.UpcastType.
type SpellObjectUpcastUpcastType string

// UserStructure defines model for UserStructure.
type UserStructure struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// PostApiDeleteCharacterJSONBody defines parameters for PostApiDeleteCharacter.
type PostApiDeleteCharacterJSONBody struct {
	Id *int `json:"id,omitempty"`
}

// PostApiDeleteItemJSONBody defines parameters for PostApiDeleteItem.
type PostApiDeleteItemJSONBody struct {
	Id *int `json:"id,omitempty"`
}

// PostApiDeleteSpellJSONBody defines parameters for PostApiDeleteSpell.
type PostApiDeleteSpellJSONBody struct {
	Id *int `json:"id,omitempty"`
}

// GetApiGetCharacterParams defines parameters for GetApiGetCharacter.
type GetApiGetCharacterParams struct {
	Id int `form:"id" json:"id"`
}

// PostApiUpdateCharacterJSONBody defines parameters for PostApiUpdateCharacter.
type PostApiUpdateCharacterJSONBody struct {
	Character *CharacterObject `json:"character,omitempty"`
	Id        *int             `json:"id,omitempty"`
}

// PostApiDeleteCharacterJSONRequestBody defines body for PostApiDeleteCharacter for application/json ContentType.
type PostApiDeleteCharacterJSONRequestBody PostApiDeleteCharacterJSONBody

// PostApiDeleteItemJSONRequestBody defines body for PostApiDeleteItem for application/json ContentType.
type PostApiDeleteItemJSONRequestBody PostApiDeleteItemJSONBody

// PostApiDeleteSpellJSONRequestBody defines body for PostApiDeleteSpell for application/json ContentType.
type PostApiDeleteSpellJSONRequestBody PostApiDeleteSpellJSONBody

// PostApiLoginJSONRequestBody defines body for PostApiLogin for application/json ContentType.
type PostApiLoginJSONRequestBody = UserStructure

// PostApiNewCharacterJSONRequestBody defines body for PostApiNewCharacter for application/json ContentType.
type PostApiNewCharacterJSONRequestBody = CharacterObject

// PostApiNewItemJSONRequestBody defines body for PostApiNewItem for application/json ContentType.
type PostApiNewItemJSONRequestBody = ItemObject

// PostApiNewSpellJSONRequestBody defines body for PostApiNewSpell for application/json ContentType.
type PostApiNewSpellJSONRequestBody = SpellObject

// PostApiRegisterJSONRequestBody defines body for PostApiRegister for application/json ContentType.
type PostApiRegisterJSONRequestBody = UserStructure

// PostApiUpdateCharacterJSONRequestBody defines body for PostApiUpdateCharacter for application/json ContentType.
type PostApiUpdateCharacterJSONRequestBody PostApiUpdateCharacterJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/delete_character)
	PostApiDeleteCharacter(w http.ResponseWriter, r *http.Request)

	// (POST /api/delete_item)
	PostApiDeleteItem(w http.ResponseWriter, r *http.Request)

	// (POST /api/delete_spell)
	PostApiDeleteSpell(w http.ResponseWriter, r *http.Request)

	// (GET /api/get_all_items)
	GetApiGetAllItems(w http.ResponseWriter, r *http.Request)

	// (GET /api/get_all_spells)
	GetApiGetAllSpells(w http.ResponseWriter, r *http.Request)

	// (GET /api/get_character)
	GetApiGetCharacter(w http.ResponseWriter, r *http.Request, params GetApiGetCharacterParams)

	// (GET /api/list_characters)
	GetApiListCharacters(w http.ResponseWriter, r *http.Request)

	// (POST /api/login)
	PostApiLogin(w http.ResponseWriter, r *http.Request)

	// (POST /api/new_character)
	PostApiNewCharacter(w http.ResponseWriter, r *http.Request)

	// (POST /api/new_item)
	PostApiNewItem(w http.ResponseWriter, r *http.Request)

	// (POST /api/new_spell)
	PostApiNewSpell(w http.ResponseWriter, r *http.Request)

	// (POST /api/register)
	PostApiRegister(w http.ResponseWriter, r *http.Request)

	// (POST /api/update_character)
	PostApiUpdateCharacter(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (POST /api/delete_character)
func (_ Unimplemented) PostApiDeleteCharacter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/delete_item)
func (_ Unimplemented) PostApiDeleteItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/delete_spell)
func (_ Unimplemented) PostApiDeleteSpell(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/get_all_items)
func (_ Unimplemented) GetApiGetAllItems(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/get_all_spells)
func (_ Unimplemented) GetApiGetAllSpells(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/get_character)
func (_ Unimplemented) GetApiGetCharacter(w http.ResponseWriter, r *http.Request, params GetApiGetCharacterParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/list_characters)
func (_ Unimplemented) GetApiListCharacters(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/login)
func (_ Unimplemented) PostApiLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/new_character)
func (_ Unimplemented) PostApiNewCharacter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/new_item)
func (_ Unimplemented) PostApiNewItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/new_spell)
func (_ Unimplemented) PostApiNewSpell(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/register)
func (_ Unimplemented) PostApiRegister(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/update_character)
func (_ Unimplemented) PostApiUpdateCharacter(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiDeleteCharacter operation middleware
func (siw *ServerInterfaceWrapper) PostApiDeleteCharacter(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDeleteCharacter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiDeleteItem operation middleware
func (siw *ServerInterfaceWrapper) PostApiDeleteItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDeleteItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiDeleteSpell operation middleware
func (siw *ServerInterfaceWrapper) PostApiDeleteSpell(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiDeleteSpell(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGetAllItems operation middleware
func (siw *ServerInterfaceWrapper) GetApiGetAllItems(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGetAllItems(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGetAllSpells operation middleware
func (siw *ServerInterfaceWrapper) GetApiGetAllSpells(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGetAllSpells(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGetCharacter operation middleware
func (siw *ServerInterfaceWrapper) GetApiGetCharacter(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiGetCharacterParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGetCharacter(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiListCharacters operation middleware
func (siw *ServerInterfaceWrapper) GetApiListCharacters(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiListCharacters(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiLogin operation middleware
func (siw *ServerInterfaceWrapper) PostApiLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiNewCharacter operation middleware
func (siw *ServerInterfaceWrapper) PostApiNewCharacter(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiNewCharacter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiNewItem operation middleware
func (siw *ServerInterfaceWrapper) PostApiNewItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiNewItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiNewSpell operation middleware
func (siw *ServerInterfaceWrapper) PostApiNewSpell(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiNewSpell(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiRegister operation middleware
func (siw *ServerInterfaceWrapper) PostApiRegister(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiRegister(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiUpdateCharacter operation middleware
func (siw *ServerInterfaceWrapper) PostApiUpdateCharacter(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, JwtBearerScopes, []string{"auth"})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiUpdateCharacter(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/delete_character", wrapper.PostApiDeleteCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/delete_item", wrapper.PostApiDeleteItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/delete_spell", wrapper.PostApiDeleteSpell)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/get_all_items", wrapper.GetApiGetAllItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/get_all_spells", wrapper.GetApiGetAllSpells)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/get_character", wrapper.GetApiGetCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/list_characters", wrapper.GetApiListCharacters)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/login", wrapper.PostApiLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/new_character", wrapper.PostApiNewCharacter)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/new_item", wrapper.PostApiNewItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/new_spell", wrapper.PostApiNewSpell)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/register", wrapper.PostApiRegister)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/update_character", wrapper.PostApiUpdateCharacter)
	})

	return r
}

type PostApiDeleteCharacterRequestObject struct {
	Body *PostApiDeleteCharacterJSONRequestBody
}

type PostApiDeleteCharacterResponseObject interface {
	VisitPostApiDeleteCharacterResponse(w http.ResponseWriter) error
}

type PostApiDeleteCharacter200JSONResponse struct {
	Character *CharacterObject `json:"character,omitempty"`
	Id        *int             `json:"id,omitempty"`
}

func (response PostApiDeleteCharacter200JSONResponse) VisitPostApiDeleteCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteCharacter401JSONResponse ErrorResponse

func (response PostApiDeleteCharacter401JSONResponse) VisitPostApiDeleteCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteCharacter500JSONResponse ErrorResponse

func (response PostApiDeleteCharacter500JSONResponse) VisitPostApiDeleteCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteItemRequestObject struct {
	Body *PostApiDeleteItemJSONRequestBody
}

type PostApiDeleteItemResponseObject interface {
	VisitPostApiDeleteItemResponse(w http.ResponseWriter) error
}

type PostApiDeleteItem200JSONResponse struct {
	Character *ItemObject `json:"character,omitempty"`
	Id        *int        `json:"id,omitempty"`
}

func (response PostApiDeleteItem200JSONResponse) VisitPostApiDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteItem401JSONResponse ErrorResponse

func (response PostApiDeleteItem401JSONResponse) VisitPostApiDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteItem500JSONResponse ErrorResponse

func (response PostApiDeleteItem500JSONResponse) VisitPostApiDeleteItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteSpellRequestObject struct {
	Body *PostApiDeleteSpellJSONRequestBody
}

type PostApiDeleteSpellResponseObject interface {
	VisitPostApiDeleteSpellResponse(w http.ResponseWriter) error
}

type PostApiDeleteSpell200JSONResponse struct {
	Character *SpellObject `json:"character,omitempty"`
	Id        *int         `json:"id,omitempty"`
}

func (response PostApiDeleteSpell200JSONResponse) VisitPostApiDeleteSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteSpell401JSONResponse ErrorResponse

func (response PostApiDeleteSpell401JSONResponse) VisitPostApiDeleteSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiDeleteSpell500JSONResponse ErrorResponse

func (response PostApiDeleteSpell500JSONResponse) VisitPostApiDeleteSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllItemsRequestObject struct {
}

type GetApiGetAllItemsResponseObject interface {
	VisitGetApiGetAllItemsResponse(w http.ResponseWriter) error
}

type GetApiGetAllItems200JSONResponse []ItemObject

func (response GetApiGetAllItems200JSONResponse) VisitGetApiGetAllItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllItems401JSONResponse ErrorResponse

func (response GetApiGetAllItems401JSONResponse) VisitGetApiGetAllItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllItems500JSONResponse ErrorResponse

func (response GetApiGetAllItems500JSONResponse) VisitGetApiGetAllItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllSpellsRequestObject struct {
}

type GetApiGetAllSpellsResponseObject interface {
	VisitGetApiGetAllSpellsResponse(w http.ResponseWriter) error
}

type GetApiGetAllSpells200JSONResponse []SpellObject

func (response GetApiGetAllSpells200JSONResponse) VisitGetApiGetAllSpellsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllSpells401JSONResponse ErrorResponse

func (response GetApiGetAllSpells401JSONResponse) VisitGetApiGetAllSpellsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetAllSpells500JSONResponse ErrorResponse

func (response GetApiGetAllSpells500JSONResponse) VisitGetApiGetAllSpellsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetCharacterRequestObject struct {
	Params GetApiGetCharacterParams
}

type GetApiGetCharacterResponseObject interface {
	VisitGetApiGetCharacterResponse(w http.ResponseWriter) error
}

type GetApiGetCharacter200JSONResponse CharacterObject

func (response GetApiGetCharacter200JSONResponse) VisitGetApiGetCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetCharacter400JSONResponse struct {
	Id      *int    `json:"id,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response GetApiGetCharacter400JSONResponse) VisitGetApiGetCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetCharacter401JSONResponse ErrorResponse

func (response GetApiGetCharacter401JSONResponse) VisitGetApiGetCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetApiGetCharacter500JSONResponse ErrorResponse

func (response GetApiGetCharacter500JSONResponse) VisitGetApiGetCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetApiListCharactersRequestObject struct {
}

type GetApiListCharactersResponseObject interface {
	VisitGetApiListCharactersResponse(w http.ResponseWriter) error
}

type GetApiListCharacters200JSONResponse []struct {
	Class   *string `json:"class,omitempty"`
	Id      *int    `json:"id,omitempty"`
	Level   *uint   `json:"level,omitempty"`
	Name    *string `json:"name,omitempty"`
	Picture *string `json:"picture,omitempty"`
	Race    *string `json:"race,omitempty"`
}

func (response GetApiListCharacters200JSONResponse) VisitGetApiListCharactersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiListCharacters401JSONResponse ErrorResponse

func (response GetApiListCharacters401JSONResponse) VisitGetApiListCharactersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetApiListCharacters500JSONResponse ErrorResponse

func (response GetApiListCharacters500JSONResponse) VisitGetApiListCharactersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiLoginRequestObject struct {
	Body *PostApiLoginJSONRequestBody
}

type PostApiLoginResponseObject interface {
	VisitPostApiLoginResponse(w http.ResponseWriter) error
}

type PostApiLogin200JSONResponse RegisteredUserStructure

func (response PostApiLogin200JSONResponse) VisitPostApiLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiLogin401JSONResponse UserStructure

func (response PostApiLogin401JSONResponse) VisitPostApiLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiLogin500JSONResponse ErrorResponse

func (response PostApiLogin500JSONResponse) VisitPostApiLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewCharacterRequestObject struct {
	Body *PostApiNewCharacterJSONRequestBody
}

type PostApiNewCharacterResponseObject interface {
	VisitPostApiNewCharacterResponse(w http.ResponseWriter) error
}

type PostApiNewCharacter200JSONResponse struct {
	Character *CharacterObject `json:"character,omitempty"`
	Id        *int             `json:"id,omitempty"`
}

func (response PostApiNewCharacter200JSONResponse) VisitPostApiNewCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewCharacter401JSONResponse ErrorResponse

func (response PostApiNewCharacter401JSONResponse) VisitPostApiNewCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewCharacter500JSONResponse ErrorResponse

func (response PostApiNewCharacter500JSONResponse) VisitPostApiNewCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewItemRequestObject struct {
	Body *PostApiNewItemJSONRequestBody
}

type PostApiNewItemResponseObject interface {
	VisitPostApiNewItemResponse(w http.ResponseWriter) error
}

type PostApiNewItem200JSONResponse struct {
	Id   *int        `json:"id,omitempty"`
	Item *ItemObject `json:"item,omitempty"`
}

func (response PostApiNewItem200JSONResponse) VisitPostApiNewItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewItem401JSONResponse ErrorResponse

func (response PostApiNewItem401JSONResponse) VisitPostApiNewItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewItem500JSONResponse ErrorResponse

func (response PostApiNewItem500JSONResponse) VisitPostApiNewItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewSpellRequestObject struct {
	Body *PostApiNewSpellJSONRequestBody
}

type PostApiNewSpellResponseObject interface {
	VisitPostApiNewSpellResponse(w http.ResponseWriter) error
}

type PostApiNewSpell200JSONResponse struct {
	Id   *int         `json:"id,omitempty"`
	Item *SpellObject `json:"item,omitempty"`
}

func (response PostApiNewSpell200JSONResponse) VisitPostApiNewSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewSpell401JSONResponse ErrorResponse

func (response PostApiNewSpell401JSONResponse) VisitPostApiNewSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiNewSpell500JSONResponse ErrorResponse

func (response PostApiNewSpell500JSONResponse) VisitPostApiNewSpellResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiRegisterRequestObject struct {
	Body *PostApiRegisterJSONRequestBody
}

type PostApiRegisterResponseObject interface {
	VisitPostApiRegisterResponse(w http.ResponseWriter) error
}

type PostApiRegister200JSONResponse RegisteredUserStructure

func (response PostApiRegister200JSONResponse) VisitPostApiRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiRegister400JSONResponse UserStructure

func (response PostApiRegister400JSONResponse) VisitPostApiRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiRegister500JSONResponse ErrorResponse

func (response PostApiRegister500JSONResponse) VisitPostApiRegisterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostApiUpdateCharacterRequestObject struct {
	Body *PostApiUpdateCharacterJSONRequestBody
}

type PostApiUpdateCharacterResponseObject interface {
	VisitPostApiUpdateCharacterResponse(w http.ResponseWriter) error
}

type PostApiUpdateCharacter200JSONResponse CharacterObject

func (response PostApiUpdateCharacter200JSONResponse) VisitPostApiUpdateCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostApiUpdateCharacter400JSONResponse struct {
	Id      *int    `json:"id,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response PostApiUpdateCharacter400JSONResponse) VisitPostApiUpdateCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostApiUpdateCharacter401JSONResponse ErrorResponse

func (response PostApiUpdateCharacter401JSONResponse) VisitPostApiUpdateCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type PostApiUpdateCharacter500JSONResponse ErrorResponse

func (response PostApiUpdateCharacter500JSONResponse) VisitPostApiUpdateCharacterResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/delete_character)
	PostApiDeleteCharacter(ctx context.Context, request PostApiDeleteCharacterRequestObject) (PostApiDeleteCharacterResponseObject, error)

	// (POST /api/delete_item)
	PostApiDeleteItem(ctx context.Context, request PostApiDeleteItemRequestObject) (PostApiDeleteItemResponseObject, error)

	// (POST /api/delete_spell)
	PostApiDeleteSpell(ctx context.Context, request PostApiDeleteSpellRequestObject) (PostApiDeleteSpellResponseObject, error)

	// (GET /api/get_all_items)
	GetApiGetAllItems(ctx context.Context, request GetApiGetAllItemsRequestObject) (GetApiGetAllItemsResponseObject, error)

	// (GET /api/get_all_spells)
	GetApiGetAllSpells(ctx context.Context, request GetApiGetAllSpellsRequestObject) (GetApiGetAllSpellsResponseObject, error)

	// (GET /api/get_character)
	GetApiGetCharacter(ctx context.Context, request GetApiGetCharacterRequestObject) (GetApiGetCharacterResponseObject, error)

	// (GET /api/list_characters)
	GetApiListCharacters(ctx context.Context, request GetApiListCharactersRequestObject) (GetApiListCharactersResponseObject, error)

	// (POST /api/login)
	PostApiLogin(ctx context.Context, request PostApiLoginRequestObject) (PostApiLoginResponseObject, error)

	// (POST /api/new_character)
	PostApiNewCharacter(ctx context.Context, request PostApiNewCharacterRequestObject) (PostApiNewCharacterResponseObject, error)

	// (POST /api/new_item)
	PostApiNewItem(ctx context.Context, request PostApiNewItemRequestObject) (PostApiNewItemResponseObject, error)

	// (POST /api/new_spell)
	PostApiNewSpell(ctx context.Context, request PostApiNewSpellRequestObject) (PostApiNewSpellResponseObject, error)

	// (POST /api/register)
	PostApiRegister(ctx context.Context, request PostApiRegisterRequestObject) (PostApiRegisterResponseObject, error)

	// (POST /api/update_character)
	PostApiUpdateCharacter(ctx context.Context, request PostApiUpdateCharacterRequestObject) (PostApiUpdateCharacterResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostApiDeleteCharacter operation middleware
func (sh *strictHandler) PostApiDeleteCharacter(w http.ResponseWriter, r *http.Request) {
	var request PostApiDeleteCharacterRequestObject

	var body PostApiDeleteCharacterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiDeleteCharacter(ctx, request.(PostApiDeleteCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiDeleteCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiDeleteCharacterResponseObject); ok {
		if err := validResponse.VisitPostApiDeleteCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiDeleteItem operation middleware
func (sh *strictHandler) PostApiDeleteItem(w http.ResponseWriter, r *http.Request) {
	var request PostApiDeleteItemRequestObject

	var body PostApiDeleteItemJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiDeleteItem(ctx, request.(PostApiDeleteItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiDeleteItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiDeleteItemResponseObject); ok {
		if err := validResponse.VisitPostApiDeleteItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiDeleteSpell operation middleware
func (sh *strictHandler) PostApiDeleteSpell(w http.ResponseWriter, r *http.Request) {
	var request PostApiDeleteSpellRequestObject

	var body PostApiDeleteSpellJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiDeleteSpell(ctx, request.(PostApiDeleteSpellRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiDeleteSpell")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiDeleteSpellResponseObject); ok {
		if err := validResponse.VisitPostApiDeleteSpellResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiGetAllItems operation middleware
func (sh *strictHandler) GetApiGetAllItems(w http.ResponseWriter, r *http.Request) {
	var request GetApiGetAllItemsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiGetAllItems(ctx, request.(GetApiGetAllItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiGetAllItems")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiGetAllItemsResponseObject); ok {
		if err := validResponse.VisitGetApiGetAllItemsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiGetAllSpells operation middleware
func (sh *strictHandler) GetApiGetAllSpells(w http.ResponseWriter, r *http.Request) {
	var request GetApiGetAllSpellsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiGetAllSpells(ctx, request.(GetApiGetAllSpellsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiGetAllSpells")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiGetAllSpellsResponseObject); ok {
		if err := validResponse.VisitGetApiGetAllSpellsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiGetCharacter operation middleware
func (sh *strictHandler) GetApiGetCharacter(w http.ResponseWriter, r *http.Request, params GetApiGetCharacterParams) {
	var request GetApiGetCharacterRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiGetCharacter(ctx, request.(GetApiGetCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiGetCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiGetCharacterResponseObject); ok {
		if err := validResponse.VisitGetApiGetCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiListCharacters operation middleware
func (sh *strictHandler) GetApiListCharacters(w http.ResponseWriter, r *http.Request) {
	var request GetApiListCharactersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiListCharacters(ctx, request.(GetApiListCharactersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiListCharacters")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiListCharactersResponseObject); ok {
		if err := validResponse.VisitGetApiListCharactersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiLogin operation middleware
func (sh *strictHandler) PostApiLogin(w http.ResponseWriter, r *http.Request) {
	var request PostApiLoginRequestObject

	var body PostApiLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiLogin(ctx, request.(PostApiLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiLoginResponseObject); ok {
		if err := validResponse.VisitPostApiLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiNewCharacter operation middleware
func (sh *strictHandler) PostApiNewCharacter(w http.ResponseWriter, r *http.Request) {
	var request PostApiNewCharacterRequestObject

	var body PostApiNewCharacterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiNewCharacter(ctx, request.(PostApiNewCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiNewCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiNewCharacterResponseObject); ok {
		if err := validResponse.VisitPostApiNewCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiNewItem operation middleware
func (sh *strictHandler) PostApiNewItem(w http.ResponseWriter, r *http.Request) {
	var request PostApiNewItemRequestObject

	var body PostApiNewItemJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiNewItem(ctx, request.(PostApiNewItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiNewItem")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiNewItemResponseObject); ok {
		if err := validResponse.VisitPostApiNewItemResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiNewSpell operation middleware
func (sh *strictHandler) PostApiNewSpell(w http.ResponseWriter, r *http.Request) {
	var request PostApiNewSpellRequestObject

	var body PostApiNewSpellJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiNewSpell(ctx, request.(PostApiNewSpellRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiNewSpell")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiNewSpellResponseObject); ok {
		if err := validResponse.VisitPostApiNewSpellResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiRegister operation middleware
func (sh *strictHandler) PostApiRegister(w http.ResponseWriter, r *http.Request) {
	var request PostApiRegisterRequestObject

	var body PostApiRegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiRegister(ctx, request.(PostApiRegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiRegister")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiRegisterResponseObject); ok {
		if err := validResponse.VisitPostApiRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiUpdateCharacter operation middleware
func (sh *strictHandler) PostApiUpdateCharacter(w http.ResponseWriter, r *http.Request) {
	var request PostApiUpdateCharacterRequestObject

	var body PostApiUpdateCharacterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiUpdateCharacter(ctx, request.(PostApiUpdateCharacterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiUpdateCharacter")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiUpdateCharacterResponseObject); ok {
		if err := validResponse.VisitPostApiUpdateCharacterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bOBL+KwLvgAN6amMn7d6ev6Vx2/iQpos4xS6wCIyxNJLYUKSWpOx6F/nvB1Ky",
	"LVmUI7/stnfwF0eRyCE5fGbmmSH/IIFIM8GRa0UGfxAVJJiCfbxKQEKgUX6afsFAm1eZFBlKTdE2gCll",
	"dPlP/VOQgPmDXyHNGJJBv+eTSMgUNBmQnHJNfKIXGZIBoVxjjJI8+SQQfI9eIX7do5d5v3svpeUeveZU",
	"7dzrafVKFOp/8gkEdTFvugwOMZpe5QelJeWxfc9ozFMs1cDzlAx+JTcfiE9uzc+V+bm5JT65Nz9X5ufm",
	"nflqfq7ekQd/PZOitWMIVuKh+SnLECTwoGVyMhW5nGRSRDSgyIOFaUY1pnVNkhsaJ9q7tM1dUyhfgJSw",
	"sIK1huBR1aTVoRtCWqqs/n4qeF4fvJP6Qxo4hEEq8k0AdpE2A5ZjZcNe+z/6/Z7fP/fPe36/13voAiQX",
	"tDikWNfsEGLT36FTLjSqlv14TzkqhV22QotJQlvdyqIKy/H9HfHJ8N0vBnqfDBRHt/fEJz+PxubN9SV5",
	"cAy41451U9fmWqYQPMZS5Dx0AApVIGmmaeHdmupsqP69YI/eNUrRVKNrMmZwpYVcOMVPBQ9V25dcTSAw",
	"M9tmERGDmbFGjV91xxW8BRnSwKNcZVSCXbpjg4ROUE5C0FARu4vaA8ggWGJlOfh5x2DDQG1bNcMZst3t",
	"vamLO+AthqTy6WoW6/YfmBCp0sAeXb06qcUInUQIOpe4dWefb7I7escZMhaA0qbFXvPvrsNO2hA8pE2M",
	"r4WPeIkj0Bh28Vwhgk4mCmYu6hMBZbmsz78bt8iDADfAsCdRCDFCHjiJWa60SGuKeHa5NE1zjrv1kaio",
	"0sv43r3fLGccJUzZTv1cOkCOaRv7wK9WJWozjJXh5jKQYgqaBor45JLTFJh3DTxkBaIvZQAczINOGJbN",
	"hhhgVjq6a1q4Y5+MuDIExT5pmtJw6QtHfIZK03j5/0cMaUC5CZy31iaJT35CuZb5E0qLBKNR+5/KQRWf",
	"7pDRuHgcM7SESEReAtyAeawRmE7MUy5ndAbMGSs39wEXLaqLgOrE/QVB1/X5d4kRGZC/na1zjLMywTh7",
	"j6A/tdpsxGDuHj9GHmKdhJOPwJyMIwEqnUISqyX3p8xlNFLiJl37VxebTqieuBkgw2gP/pdCPde5OJQ0",
	"PnRzKJvjdlu9xjTbuZtreBoiMDceKKeagqYznKQirI32su9O/GbIl2ypE1RHGtN2qDLgcQ5xKyO+Emnq",
	"pj8NSfsxjlRwXDhAW1f9v7uIwj36xHv0yfboo3bu0y3PuU+EpNwbScEjIWPcmvE0KayMgdPfYcUvGi0y",
	"lEpwWKY0ze800CVfaH5b5b/0FKrazKZSJGi4gE7+UUKwgYlrYNHLdyxyYcG0nmgJVB+XNr/HhXdpSJu2",
	"27EH0VUwozye6ESKuS2dOBGzXy7dGAu5cvFLm9K1eMIhyEdvRg0UvB96ke7iEzNQyvh2WqJz9+LbWkIV",
	"xvvLydZQP0ZNTyUUWYhhBSVTIRgCt1/p79XIbcsrZvdoSnlugh7xyT3lBjDjFBgrzTNPiU9uoPBm17n9",
	"8wGMq9I5GOO7Ekwo1WJg6pG6QasyxA376pbZmIxQtfKqSSB4gFzL1dZsi8Y2vVyH40cu5nyyHqFTRN+Q",
	"0UxeIFwcVabTfIVgqkuJM9ed6mlzhEzwLgIFj9VcyLCb1Ibd/dhp079mG0jZ00DeSSnkHapMcOXg0Skq",
	"5S5xu4RVso5mgRc5RqVX7+CvLxlKpwvLJEr8LaeKlqShkqjkSnsJzNAbvvvFRL7+hSekl9A46VrdqJDR",
	"pj0JtUdO0VJ/8y10JsXbtQf62aLMUouy5n4pNUYQaOtWuAbK7Vo+2Ujg8i8ODiZkkLh06UBf/1WNFUdM",
	"QGVdPE+nbUi6w5gqjRLDzwrlWMt8xbzqerySCBrDy/rA5Lx3/sPL3sXL8959//Xg4ofBxcWr/vnF69dv",
	"/tm7GPR6rgUMkeFKVOPraLi5Xc3t+ZyFx5qMCWHW7muSnF5APKI7BuQKZXMDv4iEhwL75xfdUFx1lg4Y",
	"V08kN8wdNEoK7LlezdilQefKFWWdUVmkhlS7g/IM5bSYQRdRjeDWFPgcWQzzde8Nmpk35FYtu/zaMOIR",
	"VxqsOxjCwqQEHw2dQPN0LXJp/n7mmjIvpDYKYugwZGfRLYq2HBUf4UznuMdpzROiv+4UzidhGq92plmi",
	"XGlyqbCPyNAQAVsLN7H7GsEQvjFYGtjmb10jNysNvf3ONj5CjDbfdGdKPN66WY4RWhNtK6wB5HuR28Ax",
	"RpusfaTMgvg9orb58KKjQiTVudukfaKCRAi2WdThX/L2gy1tqLfDDJZ0vkPpzEpYr3c9MpWBq9rpZJg0",
	"xYkWkwCUPp7RtO+RGa9enCgV9NbYmbf69w5h9ShyHqqOu5Rn7pV8h2fsy8k2EHtjTc8nV8C1pFmnlbvE",
	"P0Nh3KH+xYsXL1x4PUZQt0WBIJdUL8YmJSrm8Z+5fosgi5rA1D69X+7Al7nZAJs/WZMr2q0EJ1pn5OnJ",
	"lmwj0SiqkCEfem8heMTC+1BdFBlqb2coVdG6/6r3qmcrdhlyyCgZkItX/VeGJ2WgEzvZM8joWWgZ2yRY",
	"3n6y2iyJ9cYEbEsPvHVbK77wC6OQDMhPQunLjBYtryrNTIaASr8V4aIgL1yXJwyQZYwGVsTZF1WE9iLH",
	"bO4yDV1u1LE3mySDjIYm/VhN3NPCKxZeHt7ZbMuOcd7rHTDDmhq3pc+bt81s1X/f1Y2Lo9QoZ2xRriv0",
	"dIKVnXryyetef6eVbZt+PUt1TOkzh1wnQlKFoRn8zY5qPWjwsUjRQ9OqZqdk8GvNQn8lZo7k4ck4JYiV",
	"ebPaF0UeTN+qjZgE8Xnz4J5tt9U0RkWL78MqzHS/vUHUT53+BFuwu3Iyg25m8FlT5rAAmx11iBBFu60m",
	"MC6bfB82YCf87Y1go6j6J1hBsTMnM9jPDEyOAoxNVlXmMu2pD/gBtQeMeTADymDKCt+jPMo98BhVumEZ",
	"H9AYhvllbGRlH4i/gw/6m2q8oUovw4U6IehABK1PWzpCqOjQEUPjQvpfAaLt50CtKCrXf4LR/jCqRZVW",
	"FK1znunCo2E7bKrpWgYSUrQs2EyOGmG/5WhP6ovEmVhR9uBHYkgGWuboVxTVCFoPB4Jxp2Sqqfs71Lnk",
	"mwlR7+iUw6+e0FXKWMC50F5EeVjZkTnViUdD702ngkNjTW8h9Er65NHIC4D/Y3OIk4EdkvcZP7s2s3Zv",
	"bZ2acdfrtrbcUJz3e7lylEoKuzM9K0Mfy2Fv0M/mpfsrhpIGrtpYG6xXNfR96uarJXp950HdljthzdtK",
	"zotKz18YasJlPSsbUE+mcoipiLi4RePODG/MZ49yLTwIAluobskObcsD8sJtWqkXkZ+sWv60oNR2/L41",
	"W/Ok7VUetRwZkc/O42cpeOwtq+Nnq6L69wPOCgwvC2AuAchx3qWIXdx18MDjOH++kH2L82NUsQ/kLre1",
	"qf7fFazz4sbHqWB9PG9sjGF7tbpmB9sK1rc4P7Ba3bUEcbg77kbQl4rpPK9dAR0U96lWRwEnKO+X5BoU",
	"P1NxrsF4a9X5FueHlpw7l0G+JyTXJ7Y3lE+F44OgLEsy2I7kJV10Z4sliJeNTvx4zY97fx0/3ii4LImy",
	"R5UHzN6iN+/+N/hywbq6UObiRm718kQCerVg/EqVVm2ALfoe/ybIt6GthogLuSKsx+PkByYIXen0qdx5",
	"ik+urMF2lrNluT+XjAyIFqEglT6bbsH4E+S6XNv6YMD6mSe/wdTuPg+9SMhKjXTdpzKdZk9709crbq2t",
	"ehQB9unh6b8BAAD//+Q96pHSSwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
